### ISSUE TITLE
Tinker's contruct compatibility

### ISSUE THREAD

**Issue by Furtii** [JimiIT92/UniverseGuard2#100]
The flag "pvp" disable only minecraft PVP, player's still hurt them with tinker's weapons, i even try to set the flag invincible but it dose'nt work

**Comment by JimiIT92** [comment]
That's because for some reason the Sponge event for when an entity is damaged is not firing. I'll look into this, in the mean time you can disallow the use of tinker's items using the `/rg itemuse` command

**Comment by Furtii** [comment]
Thank you

**Comment by JimiIT92** [comment]
Version 3, with the damage flags fixes, has just been released! Check it out!
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.23
