### ISSUE TITLE
Permission nodes? + Pixelmon

### ISSUE THREAD

**Issue by ItzAnimal** [JimiIT92/UniverseGuard2#104]
Hello, I'm trying to create small pixelmon server. And I'm having trouble with creating ranks and allowing players to use accessible blocks (Pixelmon healers in spawn). As there are no permission's I can't seem to see create a system where if needs be, admins can override the area claimed with a command and build or do what ever. But for players I need a permission node to identify players using healers in spawn, so interacting essentially.

Thank you for reading and your time, Please help me <3 

~ Jeremy James / ItzAnimal

**Comment by JimiIT92** [comment]
A proper permission system is in development ;)
