### ISSUE TITLE
Rentable regions?

### ISSUE THREAD

**Issue by Ashley123477** [JimiIT92/UniverseGuard2#105]
Trying to make a mall like thing and wondering if this is possible.
Im using 2.22 and have a giant region over a whole mall, with shops inside, im trying to make like sub regions to rent, have you implemented anything like that, if not could you point me in the right direction?

**Comment by JimiIT92** [comment]
You can create other regions inside that big region and assing them a higher priority. This is essentially how global region works. Global Region has no bounds and has no priority, meaning that every other region created have a higher priority, and this way when a Player is in the Region the rules for that Region are applied. So, if you have a big Region and you want to create sub regions, you can create them and assign them a higher priority than the big region. Let's say that the big region, the mall, has a priority of 0 (which is the default priority for all regions). You can create smaller regions in the same area that have a priority, for example, of 1 or any higher number you want. By doing this, every player that will go into the smaller region will be subject to the smaller region rules, while when outside it will be subject to the mall region rules
