### ISSUE TITLE
/rg command help

### ISSUE THREAD

**Issue by ArhamR** [JimiIT92/UniverseGuard2#108]
Hi, trust all is well in these tough times,
I'm working on a modded factions server on sponge and am having some trouble with the '/rg command' command i want to make it so that in the spawn area they can not do the command '/f claim', i am typing out the command like '/rg command false f claim' and also trying it like '/rg command false fclaim' however, it still will not work.

**Comment by JimiIT92** [comment]
What factions plugin are you using? I'll see what's wrong with that ;)

**Comment by ArhamR** [comment]
I am running eagle factions

**Comment by ArhamR** [comment]
Thank you!!

**Comment by ArhamR** [comment]
So an update tired /rg command false factions and it worked but it disabled all faction commands, but is there a way to make it so that its just the claim command that is disabled, i was told that maybe the plugin doesn't support subcommands

**Comment by JimiIT92** [comment]
Yes, I can confirm, right now you can only block commands at the top level. I'll see if I can fix this so you can block subcommands too for the next release ;)

**Comment by ArhamR** [comment]
Thank you, also I don't mean to be rude or anything, or mean to rush you but is there an ETA on the next release or 3.0? again i don't mean to be rude or anything

**Comment by JimiIT92** [comment]
Next release for version 2 will come soon. Honestly I'm waiting for Sponge to release a new version, since right now there is a bug related to entity arguments and I'm waiting the new version to see if is a plugin fault or a Sponge fault (according to the forum should be a Sponge fault). 
For version 3 I honestly don't know, since I'm trying to make it as complete and extendible as possible, implementing events, permissions, apis and all that stuff. Lots of stuff that, in the Sponge enveironment, is relatively new to me. Fortunately now I have more time to spend working on, since I'm at home, so hopefully some major progreess wil be made (I still aim to release it in a few months)

**Comment by ArhamR** [comment]
Thank you, if i am not wrong the next version will be 2.18?

**Comment by JimiIT92** [comment]
No, it will be 2.23 (ps: version 3 will implement an update check so you'll also know when a new version comes out 😅).
You can track releases on Ore [https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions](https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions)
I think that you can hit the "watch" button and get notified about new releases (but I'm not entirely sure)

**Comment by ArhamR** [comment]
Lovely, thank you, and good luck, wish you nothing but the best!! <3

**Comment by ArhamR** [comment]
Oh and one last thing XD sorry, is there a way to prevent mobs from entering a region? or is that in the 3.0v as well??

**Comment by JimiIT92** [comment]
Never thinked about that... right now sadly no, I think I might add that in v2 as well, since it should just be copying the enter/exit flags but checks for entities and not players

**Comment by ArhamR** [comment]
Also with the above when i do /factions as a player it doesn't work which is supposed to happen but when i do /f it works meaning players can faction claim the spawn, i tried to do /rg command false f, but it sill doesn't work. it says "No value present"
P.S - sorry to bother you again

**Comment by JimiIT92** [comment]
Version 3, with support for sub commands, has just been released! Check it out!
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.23
