### ISSUE TITLE
/region command error

### ISSUE THREAD

**Issue by Zeexx** [JimiIT92/UniverseGuard2#11]
Hi and first thanks for your work.

My /region command didn't work.
I've got this error message:
` Error occurred while executing command 'region' for source EntityPlayerMP['Zex_'/11, l='world', x=55,74, y=4,00, z=247,10]: org/spongepowered/api/data/meta/ItemEnchantment`

Thanks in advance for your answer, sincerely!

**Comment by JimiIT92** [comment]
Released API7 version for MC-1.12.2. Read more at [https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/87](https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/87)
