### ISSUE TITLE
You don't have permission when jumping

### ISSUE THREAD

**Issue by DiabolicaTrix** [JimiIT92/UniverseGuard2#112]
Hey, when the destroy flag is set to false, every time a player jumps, it says you don't have permission. It also makes the player not take any fall damage. I am using version 2.23 (also happens on 2.22). I was also wondering why the source on github are not up to date. I would like to modify the plugin for my server.

**Comment by JimiIT92** [comment]
Hi, I will see what is causing this strange issue. The code can be found here
https://github.com/JimiIT92/UniverseGuardAPI7

I'll add this to the readme

**Comment by Vulant** [comment]
> Hey, when the destroy flag is set to false, every time a player jumps, it says you don't have permission. It also makes the player not take any fall damage. I am using version 2.23 (also happens on 2.22). I was also wondering why the source on github are not up to date. I would like to modify the plugin for my server.

Is there a mod or other plugin that makes a player damage the ground when they jump?

What other flags do you have set to false?

**Comment by DiabolicaTrix** [comment]
No, not any mod that affects the ground when a player jumps. I've done a lot of testing and the issue also happens on a fresh sponge install without any mods or plugins installed. I will link my region file but with my testing I narrowed it down to the destroy flag.
[globalregion.txt](https://github.com/JimiIT92/UniverseGuard2/files/4805744/globalregion.txt)

**Comment by JimiIT92** [comment]
Thanks for the Region file and sorry for the lack of updates on this, I got a lot of Jobs to do recently 😥 Can you do a quick test and see if it happens on version 2.21? Because with 2.22 the destroy flag code changed a bit, so it may be that

**Comment by JimiIT92** [comment]
Hi, sorry for the late response, I've been busy with my work and with version 3, which a first beta just for testing new commands will come out later this week :) Anyway, this should now be fixed in version 2.24, which can be found here :D
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.24
