### ISSUE TITLE
Can't add member's to a region with /rg add member <name> <region>

### ISSUE THREAD

**Issue by Vulant** [JimiIT92/UniverseGuard2#114]
I'm trying to add someone to a region, however it keeps telling me

Error occurred while executing command: No value present

Example:
/rg add member Vulant Test

Update:
After setting the value to a region
Ex: /rg setvalue Test minecraft:nether_star 1
Myself and others are unable to purchase the region (purchaseable regions is true in config) and none of us own any regions. 
Ex: /rg buy Test

It tells me the following: That player can't be added into more Regions!

Snippet of config below edited without the brackets and such:

"max_regions" 
    "*"=50
    all=50
    region=10

players 
    # Sets if players can be in a max amount of Regions
    "limit_player_regions"=false
    # The max number of Regions a player ca be member or owner
    "max_regions"=1
    # Sets if players can be in more Regions
    "unique_regions"=true

regions 
    # Sets if Regions must have a max size
    "limit_regions_size"=false
    # The max size a Region can be. This represents the distance between the first and the second point.
    "max_region_size"=100
    # Sets if Regions can be purchased
    "purchasable_regions"=true

**Comment by JimiIT92** [comment]
I'll check what's going on. One question: was Vulant online when you try to add to the Region? If not that could be the case

**Comment by Vulant** [comment]
> I'll check what's going on. One question: was Vulant online when you try to add to the Region? If not that could be the case

Yes, I am Vulant :)

**Comment by JimiIT92** [comment]
Oh, didn't noticed your username ahahahah okok, I'll see what's happening ;)

**Comment by Vulant** [comment]
> Oh, didn't noticed your username ahahahah okok, I'll see what's happening ;)

:) Thank you for your time!

**Comment by JimiIT92** [comment]
Hi, sorry for the late response, I've been busy with my work and with version 3, which a first beta just for testing new commands will come out later this week :) Anyway, this should now be fixed in version 2.24, which can be found here :D
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.24

**Comment by Vulant** [comment]
Just want to confirm that version 2.24 did fix the issue.

For anyone having trouble with this:

You need to first set the value of the region and purchase it before being able to add/remove players to the region. It looks like only the owner of the region is able to add/remove others, but I'm not sure about the other tenants.

You cannot use the /rg add command if nobody currently owns the region / if you do not own the region.

Purchasing regions is now fixed as well.
