### ISSUE TITLE
Plugin API

### ISSUE THREAD

**Issue by kernitus** [JimiIT92/UniverseGuard2#117]
Does UniverseGuard have any sort of API, the way WorldGuard [does](https://worldguard.enginehub.org/en/latest/developer/)? I had planned to port one of my plugins to Sponge, but it relies on creating and manipulating WorldGuard regions programmatically, and there doesn't seem to exist a WorldGuard Sponge port.

**Comment by JimiIT92** [comment]
API will be added in V3, which will feature proper events and methods to extend the plugin

**Comment by kernitus** [comment]
Alright, can I assume that won't be happening any time soon then?

**Comment by JimiIT92** [comment]
Unfortunately I don't have a timeline for V3 release... All I can say is that is half done at the moment, but my Job is taking me way too much time

**Comment by kernitus** [comment]
I see, I will have to be patient then.
