### ISSUE TITLE
exit flag didn't work?

### ISSUE THREAD

**Issue by Zeexx** [JimiIT92/UniverseGuard2#12]
Hi guys and first thanks for your work!

I'm actually trying to put this "exit" flag to false, so players shouldn't be able to leave this area BUT they can... They can't leave with "tp" like commands BUT they can pass the area's frontiers...

Shouldn't this flag should actually block players who didn't have permission to pass through?

Hope there is a solution, in advance thanks for your answer.
Sincerely.

**Comment by JimiIT92** [comment]
Yes, that flag is still work in progress, therefore there are still some bugs related to that (same with the enter flag) :/

**Comment by Zeexx** [comment]
Arf... so sad.

So, i will check this page for update and thanks for your answer!

**Comment by JimiIT92** [comment]
Implemented in version 2.6. Read more at: [https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/87](https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/87)
