### ISSUE TITLE
Console spam by this plugin

### ISSUE THREAD

**Issue by pjindras** [JimiIT92/UniverseGuard2#121]
hi, can you help me please my server console is instantly spammed by sponge - messages like this https://pastebin.com/JTStKVSK how to disable it or how to fix it ? Thanks a lot 🙂 

I am using sponge forge 1.12.2-2838-7.2.3

**Comment by JimiIT92** [comment]
It looks like there are some issues with this block `sbop:leaves_flowering` when an entity collides with. Can you tell me which mod this block comes from, so I can fix the issue? :)

**Comment by pjindras** [comment]
its Dynamic Trees Biomes o Plenty mod https://www.curseforge.com/minecraft/mc-mods/dtbop

**Comment by JimiIT92** [comment]
Hi, just an update on this Issue. I set up a local server with Biomes o Plenty and Dynamic Trees mod installed. The first thing I noticed is that I can't find the specified block, so my testing was just to place some BOP leaves, make some entities collide with them and see what happens. While doing this I see no issues or errors reported in console. By looking at the pastebin you posted I noticed something strange. The plugin class this function
```FlagUtils.getInteract``` which is the one responsible to determine if an entity is interacting with something in particular (like buttons, pressure plates, etc...). What is strange is that it tries to read the `decayable` property for leaves, however if you look into the code for that function there isn't a single line that tries to do that. So it could just be some wrong configuration, where for some reason some leaves ended up being handled as interactable blocks. To further analyze this I need more details, specifically the full list of mods installed on the server and more details about how to reproduce the issue. If possible it would be perfect to have the Region file to see if there are any issues in it as well

**Comment by J-Tinguely** [comment]
Hi, i got the same issue with the `orientation` property on `techreborn:solarpanel`.
I'm running latest sponge 1.12.2 recommended release (1.12.2-2838-7.2.3) on MCEternal lite modpack

If you want, i can do a quick test with only universeGuard2 installed as i got other plugins on the server right now, just let me know :)
(Walking on it his enough to trigger the issue)

Have a nice day !

**Comment by JimiIT92** [comment]
Yes, if is not a problem that would help. Also, if you can please share the region file as well. Can you confirm that the mod for that block is Tech Reborn?

**Comment by J-Tinguely** [comment]
I confirm that it is Tech Reborn, i just tested with only sponge and UniverseGuard2 and i still have the message.
The error appear everywhere no matter region or level-type, i said earlier that you just need to walk on it but you actually need to jump on it to trigger the error.

I'm doing a quick try with far less mods, if i find something i'll reply here tonight otherwise i will try again another day.

**Comment by JimiIT92** [comment]
Maybe it could be some flag in the world Region that is messing around with that. Can you post the log? I tried jumping as well, still got nothing, so I believe it could be some configuration that I'm missing on my side

**Comment by J-Tinguely** [comment]
I tried with a brand new config and still no luck. (`rm -rd universeguard.conf universeguard/`)

The error log : https://pastebin.com/raw/utDeypr1

**Comment by J-Tinguely** [comment]
I will try later this week with a new install of the modpack i'm currently running, i'll let you know.

**Comment by JimiIT92** [comment]
Thank you for the log, it will help me a lot understand where the problem is. I don't know why we have different results, but it seems that the problem is inside the interact flag. Have you turned off interaction for that block?
