### ISSUE TITLE
PVP flag controls PVE

### ISSUE THREAD

**Issue by Minurv** [JimiIT92/UniverseGuard2#123]
Attempting to attack a mob while PVP is disabled will block it without permission. Once PVP is reenabled mobs are attackable again. Using UniverseGuard 2.24 and SpongeForge 7.2.3

**Comment by JimiIT92** [comment]
Fixed in version 2.25
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.25
