### ISSUE TITLE
PVP flag + customNPC

### ISSUE THREAD

**Issue by XuTTcTeP** [JimiIT92/UniverseGuard2#124]
PVP flag does not allow to interact with NPCs from customNPC mod

**Comment by JimiIT92** [comment]
Hi. I'm sorry but I don't know very well how to use the Custom NPC mod. I tried to spawn a simple npc and right click him and it says Hello, so I guess there is a particular case in which this happens. However, I think this might be related to this issue
https://github.com/JimiIT92/UniverseGuard2/issues/123
which has been solved in version 2.25. So let me know if the issue still occur in the new release, and if so please add some details so I can reproduce exactly the issue :)
You can find the new release here
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.25

**Comment by XuTTcTeP** [comment]
Thank you, everything is working now!
