### ISSUE TITLE
[Minor] /rg add requires "region" permission even if "all" permision is set

### ISSUE THREAD

**Issue by EragonRussia** [JimiIT92/UniverseGuard2#127]
Hello! Thanks for 2.26, that fixed error output. Now users (admins) have "you do not have permission to use this command". I fixed that by adding "region" perm to admin group in luckyperms. According to [wiki](https://github.com/JimiIT92/UniverseGuard2/wiki/rg-add), you must have "all" permission for that, not "region. Not a big problem but can be misleading.

Before adding new permission:
![изображение](https://user-images.githubusercontent.com/68070406/92483184-3497d700-f1f1-11ea-9cb5-cfcd7e080239.png)
After (works!):
![изображение](https://user-images.githubusercontent.com/68070406/92483225-3e213f00-f1f1-11ea-9cb6-1f3acc44c828.png)

**Comment by JimiIT92** [comment]
That's correct, I guess I forgot to update the Wiki 😅 Actually I'll see if there's anything else missing, thanks for the report!
