### ISSUE TITLE
[Feature Request] Adding whole luckperms group in the region

### ISSUE THREAD

**Issue by EragonRussia** [JimiIT92/UniverseGuard2#128]
Hello! I have a small RP server and adding people in regions of faction is very hard job (because they have a lot of regions...). I know you are planning smth like that for UG3, but its release date is quite... Uncertain :D

**Comment by JimiIT92** [comment]
Defining groups (or tags) for regions/players/etc... is planned, so that will be possible ;)

**Comment by EragonRussia** [comment]
Ok, will wait :(
