### ISSUE TITLE
bug with pistons

### ISSUE THREAD

**Issue by XuTTcTeP** [JimiIT92/UniverseGuard2#129]
Pistons are not working in regions. There is no difference if you enable of disable pistons in region they are still not working.
Here is a video and region file.
Video: https://youtu.be/DPmEPPMPMLo
Region file: https://mega.nz/file/kBonyRTS#pkYcnF_TBmO8YRXCl5zY78ThodDAoiEiZUV9Okhfue0

**Comment by JimiIT92** [comment]
Thank you for the report and the additional files. Will look into that as soon as possible

**Comment by JimiIT92** [comment]
Fixed in version 2.28
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.28
