### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by kimkik161rus** [JimiIT92/UniverseGuard2#131]
Hi, version minecraft 1.12.2
1) where can I view the list of permissions? (LuckPerms doesn't see this plugin) 2) How do I add my own permission? (to distribute the number of privates for Donat groups)

**Comment by JimiIT92** [comment]
Custom permissions are currently not supported, they will be in the next major release (which will be 3.0). Right now there are only 2 permissions you can specify, which can be found here
https://github.com/JimiIT92/UniverseGuard2/wiki/config#permissions
