### ISSUE TITLE
PERMS PLACE DESTROY 

### ISSUE THREAD

**Issue by CEONOS** [JimiIT92/UniverseGuard2#134]
region is set flags are all set, /rg flag flag place false /rg flag flag destroy false then /rg save. layers can still break blocks in my spawn. but they cant place. i have been trying to secure my spawn for days now . I am limted on mods/plugs because i have an RLCraft server. this is my only hope at this point. everything seemed to work fine exept that one thing. the most important thing. pls halpregion is set flags are all set, /rg flag flag place false /rg flag flag destroy false then /rg save. layers can still break blocks in my spawn. but they cant place. i have been trying to secure my spawn for days now . I am limted on mods/plugs because i have an RLCraft server. this is my only hope at this point. everything seemed to work fine exept that one thing. the most important thing. pls halp

**Comment by JimiIT92** [comment]
Please share your region file so I can replicate your situation and test the bug in a local server

**Comment by JimiIT92** [comment]
An update on this: MC servers has a default "vanilla" spawn protection. This spawn protection overrides the plugin protection. Your region is probably inside the default spawn area of the server, so the vanilla protection comes in action. If this is your case you can avoid this by ssetting the **spawn-protection** value to 0 in the **server.properties** file. Let me know if this fixes your problem, I'm trying to see if there is way to take over the vanilla one. If your region is not in the default spawn area than please post your region file here so I can test the issue using your exact region settings
