### ISSUE TITLE
Getting this error: "Could not pass the event FMLServerStartedEvent to an Event Listener!"

### ISSUE THREAD

**Issue by ivandis** [JimiIT92/UniverseGuard2#135]
Howdy,

Mod plugin stopped working out of the blue.  Was playing with config files, but couldn't see any changes that were made that could've made this occur.  Ran differences between old config files and the current ones and there are no significant differences that would cause this issue.

https://pastebin.com/9XNihimW

Let me know if you've seen this before!

**Comment by ivandis** [comment]
Issue is definitely related to the configuration files as fresh configuration files do not present this error.
[Erronious Files.zip](https://github.com/JimiIT92/UniverseGuard2/files/5559589/Erronious.Files.zip)

**Comment by ivandis** [comment]
MC 1.12
Forge 14.23.5.etc

Only thing I can potentially think of as an issue is that there are certain variables in the configuration files per region that do not correspond with the version of MC that I'm currently running on my server thus creating issues.

**Comment by JimiIT92** [comment]
Never seen an error related to config files. Probably yeah, there's someting wrong in the current config. I'll check your files as soon as possible ;)

**Comment by ivandis** [comment]
Thanks!

**Comment by JimiIT92** [comment]
I found the issue is in the json file for the **world** region. You have an unclosed flag value at line 77, the **falldamage** flag. In fact if you remove this file from your regions everything works as well. I'll post here the correct file :)

[world.zip](https://github.com/JimiIT92/UniverseGuard2/files/5580003/world.zip)

**Comment by ivandis** [comment]
Thank you very much for your quick response!  I sent you a tip on PayPal for your troubles.

**Comment by ivandis** [comment]
I must've just missed that closing brace; normally I'm good at making sure they're there.  I can't tell you how many times I ran diff checkers between my files and the default ones.

**Comment by JimiIT92** [comment]
Thank you so much for the support! ❤ Yeah, mistakes happens, unfortunately 😅
