### ISSUE TITLE
water

### ISSUE THREAD

**Issue by CaiProgramming** [JimiIT92/UniverseGuard2#136]
water stops flowing but if I take the flag off it doesn't start flowing again.

**Comment by JimiIT92** [comment]
Which flag is causing this issue?

**Comment by CaiProgramming** [comment]
Actually just figured it out. It's the place command. and it seems to break my Redstone on my server as well. if its set to false

**Comment by JimiIT92** [comment]
That's probably because it sees the redstone changing property as a new block being placed. You can fix this temporarly by excluding the redstone dust block from the place flag

**Comment by CaiProgramming** [comment]
how do i do this?

**Comment by CaiProgramming** [comment]
though the water also still doesnt flow

**Comment by JimiIT92** [comment]
Using the `/rg excludeblock` command
https://github.com/JimiIT92/UniverseGuard2/wiki/rg-excludeblock

Yeah, the place flag is also preventing fluids from being placed or flow. You should get the same bug with lava as well. A fix will be released later today
