### ISSUE TITLE
Protected Blocks flags disappear

### ISSUE THREAD

**Issue by bigd9804** [JimiIT92/UniverseGuard2#137]
So I set my spawn protection to 0 in the server.properties hoping it would help my issue it didn't. Every time I create a flagged region to protect my spawn the flags would stay until my server restarts then they would disappear. So an example would be /rg flag flag destroy false then /rg save. I even named my region /rg name spawn then /rg save. The commands would work but when my server restarts all the commands I setup to protect my spawn just disappear. Can you please tell me what I am doing wrong or what is going on plz?

**Comment by JimiIT92** [comment]
From what you said you are doing everything correct. This sounds really strange, can you share me the Region file and tell me how you restart the server? Just launching a /stop command and then running it again or are you using something else (like a command or a plugin?) Also, which versions of Sponge and/or Forge is the server using?
