### ISSUE TITLE
Water and lava not flowing

### ISSUE THREAD

**Issue by Phil7789** [JimiIT92/UniverseGuard2#138]
While using UniversGuard2 water and lava won't ever flow. The flags are globally set to true and not altered in local regions. The entire world is affected by this.

I tried this with only Sponge and UniverseGuard installed, so there shouldn't be any conflicting mods.
I then tried setting the flags to false and to true again, unfortunately with no effect.

Sponge: **1.12.2-2838-7.3.0**
UniverseGuard: **2.31**

If you need any other information please let me know

**Comment by Dojo215** [comment]
I thought it was just me going crazy, but our server has that too. Someone pls fix? Kinda game breaking tbh :/

(exact same versions as above, even tried reloading and restarting server)

**Comment by JimiIT92** [comment]
Kinda strange, can you share the Region file so I can use your exact region configuration?

**Comment by Dojo215** [comment]
Sorry for taking so long, here's my world at least, but we do have a few mods that add dimensions but they're all set the same, let me know if you need them too
[093ff07c-e661-4ce9-8832-e053ad08f68e.txt](https://github.com/JimiIT92/UniverseGuard2/files/5691579/093ff07c-e661-4ce9-8832-e053ad08f68e.txt)

**Comment by JimiIT92** [comment]
If the bug happens in the vanilla dimensions too than is not necessary. I'll let you know if there any issues where I may ask that list

**Comment by Druwan-ctrl** [comment]
I have the same issue, in the vanilla dimension

**Comment by Mike5357** [comment]
Also experiencing this issue immediately after updating from 2.29 to 2.31

**Comment by Feryzz** [comment]
I have same problem

**Comment by CarryTI** [comment]
Is there any news on this topic? This problem also occurred on my server

**Comment by JimiIT92** [comment]
Sorry all, I got a bit busy this month due to work releases, ills and other private stuffs (relocating, ecc..). I will try to find a fix today, so expect some updates later today or tomorrow ;)

**Comment by JimiIT92** [comment]
Version 2.32 has just been released! https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.32
Let me know if there are any issues related :)
