### ISSUE TITLE
Pixelmon (Healer / PC)

### ISSUE THREAD

**Issue by juangj-opg** [JimiIT92/UniverseGuard2#139]
Hello. Im using Pixelmon with UniverseGuard2. I can use Healer or the PC, but the others users cant. I try everything and nothing (permissions, commands, nothing).
The version of UniverseGuard2 is : UniverseGuard-2.31
The  version of Pixelmon is : Pixelmon-1.12.2-8.1.2-universal

P.S.: Im spanish, sorry for my english.

**Comment by Vulant** [comment]
Check to see if the healer or PC block (I'm assuming it's a block) changes to a different block when used. If you have the place / destroy flags set to false then you'd need to exclude those blocks to allow it to work.

**Comment by JimiIT92** [comment]
I've just setup a local server with Pixelmon Reforged 1.12.2-8.1.2 installed. I tried with a non-op account but so far I was able to interact with the Healer having the place or the destroy flag set to false in the global region. Please share you Region file so I can replicate your exact situation, maybe some flags are conflicting each others
