### ISSUE TITLE
Flag not found: /rg flag mobspawn

### ISSUE THREAD

**Issue by wpmidia** [JimiIT92/UniverseGuard2#14]
**/rg flag mobspawn**
This flag "mobspawn" does not exist!

**Comment by DragaoNimhe** [comment]
Hope I'm not breaking any rules by commenting here, but we were able to get mobspawning set to false in a region on our server, and it does in fact disable the spawning of mobs for us. Hope that helps!

**Comment by JimiIT92** [comment]
Version 2.7 released! :D 
https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/116
