### ISSUE TITLE
players can destroy in a region

### ISSUE THREAD

**Issue by Feryzz** [JimiIT92/UniverseGuard2#140]
In my server pixelmon reforged player can destroy a block if they try to smash it repeatedly.

I'm using latest version of your plugin.

**Comment by Vulant** [comment]
Is it any block or just a specific one from a mod?

Also, when you relog, is the block still gone or is it back?

**Comment by JimiIT92** [comment]
I've just setup a local server with pixelmon reforged 1.12.2-8.1.2 installed. I tried with a non-op account to break blocks in the global region that has the `destroy` flag set to false. I tried different vanilla and mod blocks but sso far I can't reproduce the issue. So, as Vulant said, is it just a specific block that is causing the issue? And is it a client-side only problem (the block reappears if you relog/restart the game) or not?
