### ISSUE TITLE
Chest cant be open by anyone

### ISSUE THREAD

**Issue by DarkStar0790** [JimiIT92/UniverseGuard2#143]
While using UniversGuard2 the chest cant be open by any player in the world. The flag come by default as false and seems to be altering globally all the world.

DEFAULT VALUE
false
VALUE MEANS
true: Any player that is not a member of a Region can use chests inside the Region
false: Only players that are member of the Region or that has permissions can use chests inside the Region

As this flag is by default false, alter all world, and any player will be able to open chest in any part of the world unless they are in a region as members.

I tried this with only Sponge and UniverseGuard installed, so there shouldn't be any conflicting mods.

To fix this, you need to make a region and inside that region you need to set the chest flag to true, then people can open chest inside that region.
Or if you will have a region for a specific group/clan, then if you add them to that region, they will be able to open chest inside that region because the chest flag is in false by default.

Please fix this :(

**Comment by Vulant** [comment]
Go in-game and try /rg edit world and see if the flag for chests is set to false. Sometimes config doesn't like to listen

**Comment by DarkStar0790** [comment]
Alright, I will try that and I'll let you know! thanks

**Comment by JimiIT92** [comment]
Let me know if doing that solve the issues, basically refreshing the Region. Is really strange that default config values are ignored or misread

**Comment by DarkStar0790** [comment]
yes it fix the issue! thanks

**Comment by JimiIT92** [comment]
Strange, I will see if there is anything going on that causes this. Does it also occur in latest release?

**Comment by Vulant** [comment]
Did someone else have the same issue Jim?

**Comment by JimiIT92** [comment]
> Did someone else have the same issue Jim?

Looks like not. Closing the issue
