### ISSUE TITLE
[1.12.2] Item Frames can be destroyed even when destroy flag is false

### ISSUE THREAD

**Issue by Vulant** [JimiIT92/UniverseGuard2#144]
Version: UniverseGuard-2.31

When creating a region and setting the destroy flag to false, as well as the interact with item frame set to false, I can still destroy the item on the item frame, the item frame itself, and interact with it.

This happens with vanilla item frames as well as modded item frames like the clear frame from Tinker's Construct.

**Comment by JimiIT92** [comment]
Version 2.32 has just been released! https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.32
Let me know if there are any issues related :)
