### ISSUE TITLE
Can't make water flow

### ISSUE THREAD

**Issue by TheElementalDragon** [JimiIT92/UniverseGuard2#145]
I set the flag waterflow to true in "world" yet water outside my region still won't flow

**Comment by JimiIT92** [comment]
Which version are you using?

**Comment by TheElementalDragon** [comment]
I'm using version 2.31

**Comment by MkUltra2000** [comment]
I have the same issue, further more i can't pick up water with buckets either.
using version 2.31 of Universe Guard
Using version 7.3.0 of Sponge
and running server on Minecraft 1.12.2

**Comment by TheElementalDragon** [comment]
I'll try to give as much info as possible real quick, I can confirm that players on my server can't pickup water or lava in buckets, lava also doesn't flow yet lava flow is set to true as well. Otherliquids flow I cannot confirm as we don't have Mods that add other liquids. Changing the settings in the config instead of the game and restarting the server did not change this behavior

**Comment by ObnoxiousZombi** [comment]
commenting for a followup since i'm having the same issue

**Comment by JimiIT92** [comment]
Try to upgrade to version 2.32, which got released some days ago and aims to fix the fluids issue. You can find it here
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.32
Let me know if the issue still occurs. If it does please share a Region file where the issue occurs

**Comment by ObnoxiousZombi** [comment]
I can confirm that upgrading to 2.32 fixed the issue, thank you sir

**Comment by MkUltra2000** [comment]
> Try to upgrade to version 2.32, which got released some days ago and aims to fix the fluids issue. You can find it here
> https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.32
> Let me know if the issue still occurs. If it does please share a Region file where the issue occurs

Hey i have upgraded to version 2.32 and now water/lava is flowing as intended (can't check other liquids but i assume they go through a similar process so they should be working fine) But when ever i try to use a empty bucket to pick up any liquids it doesn't give me the liquid i was just wondering if there is a permission thing i have to change as i check the global config and couldn't see anything related.

**Comment by JimiIT92** [comment]
May be the destroy flag interfering with that, since you are essentially "destroying" the water. I might change that so the liquidflow flags also controls how buckets works

**Comment by JimiIT92** [comment]
Version 2.33 should now fix the fluid pickup issue. The pickup logic is now handled by the corresponding flow flag
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.33
