### ISSUE TITLE
Water Pickup issue

### ISSUE THREAD

**Issue by DingDongDIngles** [JimiIT92/UniverseGuard2#148]
Whenever I try to pickup water in a bucket it doesn't let people who aren't op. Not sure what flag its under for some reason.

**Comment by Vulant** [comment]
Make sure spawn protection isn't the case. I feel like that may be the reason why as you mention OP.

Try to pickup water in a bucket somewhere far far away from spawn or set spawn protection to 0 in your server.properties

**Comment by JimiIT92** [comment]
Sounds similar to this bug
https://github.com/JimiIT92/UniverseGuard2/issues/145
As I said there it might be the destroy flag interfering with this. If so I might change the behavior just for buckets so they are handled by the flowing flags as well

**Comment by hypersmc** [comment]
@JimiIT92 I'm using 2.32 and my users can't pick up any fluids `/rg flag flag destry true` still doesn't make it work

**Comment by JimiIT92** [comment]
> @JimiIT92 I'm using 2.32 and my users can't pick up any fluids `/rg flag flag destry true` still doesn't make it work

Understand. Will try different combinations with destroy/flag/waterflow flags to see when this occurs 👍🏼

**Comment by MatessCZ** [comment]
Hi, experiencing same bug, I even tried to add bucket to list of allowed items, tried to exclude water from region but still non-OP-players cant pick it up. At least bucket gets filled up.

**Comment by SimonMage** [comment]
Ciao, scusa il disturbo. Potrei sapere quando sarà possibile il download di una versione che ripara anche solo questo problema? Non permettendo ai player di prendere l'acqua mi obbliga a rimuovere il plugin ma non voglio perché questo plugin mi piace molto. 

PS: So che non è la sezione giusta, ma potresti aggiungere la flag "blocked-cmds" per bloccare i comandi? Sarebbe molto utile.
Saluti :)

**Comment by hypersmc** [comment]
> Ciao, scusa il disturbo. Potrei sapere quando sarà possibile il download di una versione che ripara anche solo questo problema? Non permettendo ai player di prendere l'acqua mi obbliga a rimuovere il plugin ma non voglio perché questo plugin mi piace molto. 
> 
> 
> 
> PS: So che non è la sezione giusta, ma potresti aggiungere la flag "blocked-cmds" per bloccare i comandi? Sarebbe molto utile.
> 
> Saluti :)



@SimonMage uh? English?

**Comment by SimonMage** [comment]
Hi, sorry for bothering you. May I know when it will be possible to download a version that fixes this problem alone? Not allowing the players to take the water forces me to remove the plugin but I don't want to because I really like this plugin.

PS: So that's not the right section, but could you add the "block-cmds" flag to block commands? It would be very useful.
Greetings :)

--;English Version;--

**Comment by hypersmc** [comment]
> Hi, sorry for bothering you. May I know when it will be possible to download a version that fixes this problem alone? Not allowing the players to take the water forces me to remove the plugin but I don't want to because I really like this plugin.
> 
> 
> 
> PS: So that's not the right section, but could you add the "block-cmds" flag to block commands? It would be very useful.
> 
> Greetings :)
> 
> 
> 
> --;English Version;--

@SimonMage there is no current fix for it. For now you will have to uninstall it or wait for an update to happen.

**Comment by Vulant** [comment]
Hey Jim, 

I can pick up water but it will tell me that I don't have permission to do that. Oddly enough, the same message appears with placing down lilypads. I didn't see a message for boats though.

**Comment by benllben** [comment]
Hey @JimiIT92, I have managed to locate the issue that is preventing water from being picked up. 

By commenting out some code in the FlagDestoryListener, I was now able to pick up water as intended.


	public void onBlockDestroyedByPlayer(ChangeBlockEvent.Break event) {
		if (!event.getTransactions().isEmpty()) {
			BlockSnapshot block = event.getTransactions().get(0).getOriginal();
			BlockType type = block.getState().getType();
			if(event.getContext().containsKey(EventContextKeys.PISTON_EXTEND) ||
					event.getContext().containsKey(EventContextKeys.PISTON_RETRACT) ||
					type == BlockTypes.PISTON_EXTENSION ||
					type == BlockTypes.PISTON_HEAD) {
				return;
			}
			if (block.getLocation().isPresent() &&
					event.getContext().containsKey(EventContextKeys.SPAWN_TYPE) &&
					event.getContext().get(EventContextKeys.SPAWN_TYPE).get() != SpawnTypes.CUSTOM &&
					(event.getContext().containsKey(EventContextKeys.OWNER) || event.getContext().containsKey(EventContextKeys.PLAYER_BREAK))) {
				Player player = event.getCause().first(Player.class).orElse(null);
                Region region = RegionUtils.getRegion(block.getLocation().get());
                /*if(region != null && FlagUtils.isExcludedFromDestroy(region, type)
						&& (player == null || !PermissionUtils.hasPermission(player, RegionPermission.REGION))) {
                    if(region.getFlag(EnumRegionFlag.DESTROY)) {
                        event.setCancelled(true);
                        MessageUtils.sendHotbarErrorMessage(player, RegionText.NO_PERMISSION_REGION.getValue());
                    }
                } else {*/
                    this.handleEvent(event, block.getLocation().get(), player);
                //}
			}
		}
	}

I hope this helps you out with diagnosing the underlying issue.

**Comment by JimiIT92** [comment]
> Ciao, scusa il disturbo. Potrei sapere quando sarà possibile il download di una versione che ripara anche solo questo problema? Non permettendo ai player di prendere l'acqua mi obbliga a rimuovere il plugin ma non voglio perché questo plugin mi piace molto.
> 
> PS: So che non è la sezione giusta, ma potresti aggiungere la flag "blocked-cmds" per bloccare i comandi? Sarebbe molto utile.
> Saluti :)

Ciao, per la prima domanda ti direi a breve, sto già analizzando il problema. Per la seconda c'è già la possibilità di bloccare comandi all'interno di una regione, trovi la documentazione qui: https://github.com/JimiIT92/UniverseGuard2/wiki/rg-command

**Comment by JimiIT92** [comment]
> Hey @JimiIT92, I have managed to locate the issue that is preventing water from being picked up.
> 
> By commenting out some code in the FlagDestoryListener, I was now able to pick up water as intended.
> 
> ```
> public void onBlockDestroyedByPlayer(ChangeBlockEvent.Break event) {
> 	if (!event.getTransactions().isEmpty()) {
> 		BlockSnapshot block = event.getTransactions().get(0).getOriginal();
> 		BlockType type = block.getState().getType();
> 		if(event.getContext().containsKey(EventContextKeys.PISTON_EXTEND) ||
> 				event.getContext().containsKey(EventContextKeys.PISTON_RETRACT) ||
> 				type == BlockTypes.PISTON_EXTENSION ||
> 				type == BlockTypes.PISTON_HEAD) {
> 			return;
> 		}
> 		if (block.getLocation().isPresent() &&
> 				event.getContext().containsKey(EventContextKeys.SPAWN_TYPE) &&
> 				event.getContext().get(EventContextKeys.SPAWN_TYPE).get() != SpawnTypes.CUSTOM &&
> 				(event.getContext().containsKey(EventContextKeys.OWNER) || event.getContext().containsKey(EventContextKeys.PLAYER_BREAK))) {
> 			Player player = event.getCause().first(Player.class).orElse(null);
>             Region region = RegionUtils.getRegion(block.getLocation().get());
>             /*if(region != null && FlagUtils.isExcludedFromDestroy(region, type)
> 					&& (player == null || !PermissionUtils.hasPermission(player, RegionPermission.REGION))) {
>                 if(region.getFlag(EnumRegionFlag.DESTROY)) {
>                     event.setCancelled(true);
>                     MessageUtils.sendHotbarErrorMessage(player, RegionText.NO_PERMISSION_REGION.getValue());
>                 }
>             } else {*/
>                 this.handleEvent(event, block.getLocation().get(), player);
>             //}
> 		}
> 	}
> }
> ```
> 
> I hope this helps you out with diagnosing the underlying issue.

Thank you for the hint ;)

**Comment by JimiIT92** [comment]
Version 2.33 should now fix the fluid pickup issue. The pickup logic is now handled by the corresponding flow flag
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.33
