### ISSUE TITLE
 The barrier can be crossed by riding a horse

### ISSUE THREAD

**Issue by DarkStar0790** [JimiIT92/UniverseGuard2#149]
Hello, In my server, people have been trying to cross the barrier and the have achive it by getting a horse, ride it and then go inside the barrier with the horse.  Seems that the barrier detected the horse and not the player that is riding it so the barrier will allow the player to enter into a barrier where the enter flag is set to false.

**Comment by JimiIT92** [comment]
Not sure what are you referring to as "barrier". Is it the barrier block or the world border? Anyway from what I understand players are able to enter Regions even if they aren't supposed to if they are riding a horse, is it correct? I will look into this

**Comment by DarkStar0790** [comment]
Sorry for my bad english, with barrier i mean the border of the region that is created with universe guard.  So if you create a region, and set the flag enter false.  Only members can enter to the region, thats working good, but someone that is not member of the region if ride a horse, will be able to enter and exit to that region.  Unless you set flag exit false. Then that player will not be able  to scape from the region if he enter using a horse.

**Comment by JimiIT92** [comment]
Ok, will check this ;)

**Comment by JimiIT92** [comment]
Version 2.33 should now fix the enter flag issues. Note that further improvements will be made in next release, to avoid the current "glitchy" push back, which still keep players away from the Region but it could be "disturbing" after a while
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.33
