### ISSUE TITLE
./rg or /region not giving selection item

### ISSUE THREAD

**Issue by DragaoNimhe** [JimiIT92/UniverseGuard2#15]
Hello, as my title states, when we type /rg or /region nothing happens.  As a result we are unable to use the plugin or any of its features, hopefully you can help! We are running version 1.12.2 of minecraft, spongeforge-1.12.2-2611-7.1.0-BETA-2916.jar, and UniverseGuard-2.6-AP17 (for 1.12.2). Other commands work, it is just /rg and /region that return nothing. Let me know if you need any more info!

**Comment by JimiIT92** [comment]
In 1.12.2 i've noticed sometimes the selector goes in the inventory, not in the hotbar. Check your inventory and let me know if is there (by the way i'll see if i can put the selector directly into the hotbar to avoid confusion) :)

**Comment by Brycey92** [comment]
Does /rg or /region output anything to chat?

**Comment by DragaoNimhe** [comment]
No, nothing is given and nothing is output to chat or console at all.

**Comment by JimiIT92** [comment]
That's strange, will look into this problem. Thank you for your report ;)

**Comment by DragaoNimhe** [comment]
Thanks, if you'd like to join the server and see for yourself let me know!

**Comment by JimiIT92** [comment]
Version 2.7 released! :D 
https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/116
