### ISSUE TITLE
Flags of add effect not working

### ISSUE THREAD

**Issue by DarkStar0790** [JimiIT92/UniverseGuard2#150]
I have made a regione protected and then i set the flags with some added effect:

/rg effectadd minecraft:absorption
/rg effectadd minecraft:Nausea

Etc.. but they are not working.  Players can enter to the region but the effects will not apply to the players.  Please help :(

**Comment by JimiIT92** [comment]
Make sure the use_effects option is enabled in the plugin config file. If this is disabled than the effects won't be applied to Regions

**Comment by DarkStar0790** [comment]
Ok i will change that in the config file and test.  Thanks!

**Comment by JimiIT92** [comment]
Let me know if that was the issue :)

**Comment by DarkStar0790** [comment]
Yes it was! thanks!
