### ISSUE TITLE
Protections not working when TPS drops

### ISSUE THREAD

**Issue by Tomographix** [JimiIT92/UniverseGuard2#154]
Hello,

I have noticed an issue where if the TPS on the server drops below 20 (doesn't have to be by much) that the protections seem to not work and players can break blocks.

We are using UniverseGuard2 version 2.32 and spongeforge-1.12.2-2838-7.3.0.jar

Thank you

**Comment by JimiIT92** [comment]
![2021-03-24_21 20 37](https://user-images.githubusercontent.com/14943331/112378436-3afe2400-8ce7-11eb-8518-2d45b5d12092.png)
Sorry for late response, I tried to overload a local server with a Cowpocalypse and tried to break some blocks, even tried to break multiple blocks at the same time. Even with this mess, where both client and server where literally screaming, I saw no issue on preventing blocks from being broken. Sure, there was a slight lag from when you break the block and when it reappear, but is a client lag issue that unfortunately the plugin has no control over it (you can get a similar result sometime when removing water in lakes, where the hole appears to be empty but after a while it reappear)

**Comment by Alydus** [comment]
This does happen for me, but I'm pretty sure every case has been resolved by all those that had the chunk loaded on their client simply reconnecting, and the blocks come back, or a server restart. Some sort of desync thing going on, not sure if theres any fix for it.

**Comment by JimiIT92** [comment]
This is certainly a client-side issue, which unfortunately I have little to none control. I've done so the place and break event listeners are now running as first events and before any modifications actually occurs. This is the only thing I am aware of I can try to solve this, let me know if it still occurs with version 2.35 that has this fix implemented ;)
You can find the new version here: https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.35
