### ISSUE TITLE
[1.12.2] Unable to Stop Mod Explosions in Protected Areas

### ISSUE THREAD

**Issue by SirR3AL** [JimiIT92/UniverseGuard2#155]
Hello,

So I am trying to have Universe Guard protect the spawn region of my server, I also have mods installed such as 'IC2' and 'Flan's Mod' running on the server as well. I enabled the flag that blocks TNT explosions in protected areas but explosions that are not 'vanilla' are able to bypass it. Along with that for say IC2's Mining Laser is able to destroy blocks in this region too. Is there a flag I need to enable or could this be a possible feature added? I feel this may be beneficial since SpongeForge's primary bases is allowing it to be usable with forge mods.

**Comment by SidewinderDX** [comment]
Hey, there is also a flag called "otherexplosions" did you tried that one also?

**Comment by SirR3AL** [comment]
No I did not, I didn't see it in the Wiki so I did not know it existed. I'll go try it out!
