### ISSUE TITLE
Picking up fluids issue

### ISSUE THREAD

**Issue by DarkStar0790** [JimiIT92/UniverseGuard2#156]
After upgrading to the last version of UniverseGuard2 V2.33 now anyone in my server cant break the water blocks.  They can fill the water bucket but the water block will still there.  This happen to all the world to all players.
I have the destroy true in world and also the water and lava flows in true.  Any ways they still not able to break the water block.
I make a fast edition and change the destroy, water and lava flows in world from true to false. then save, then change them again to true.  Issue still there.
I do the same on one region to test, and not members still be able to pickup water but not able to destroy water block. also the members of the region are able to pickupwater but not to destroy water block.
Also the farms from all the clans where destroyed after the update of the Mod to V2.33.
So after all my test where failed to resolve the issue, i had to go back to V2.29.
Please help me with this so i can use V2.33 or another version more updated without having this issues

**Comment by Vulant** [comment]
See #153 Jim explained what's going on here for the most part.

**Comment by JimiIT92** [comment]
Yes, fluids pick up is good for some while is odd for others. You can expect some changes in the next version, which I aim to release this week, that hopefully will make everyone ok 😅

**Comment by JimiIT92** [comment]
Version 2.34 has just been released, and it contains some changes to how picking/placing fluids works. Check it out here! ;)
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.34
