### ISSUE TITLE
Unable to add players to a region

### ISSUE THREAD

**Issue by benllben** [JimiIT92/UniverseGuard2#157]
When I attempt to do `/rg add member/owner playername regionname` I always receive "This player is already a member of that region". I does not matter if it is a brand new region, old region, nested or non nested region, it does not work. I have also attempted to do `/rg edit regionname` first.

Edit: It would also be great if we could add players to a global region (staff, builders) so they can override all regions in that world.

**Comment by JimiIT92** [comment]
Can you share a region file where this is happening? Also, for global members, you can add the universeguard.region permission to moderators and they will bypass most of the region restrictions

**Comment by benllben** [comment]
Sorry for the delay. This still occurs on the latest version with brand new regions.
Attached is an example as requested. Notice how 2 players are able to be added, however other players (online or offline) cannot be added as it says they are already a member of a region.

It seems like if you are added to a region, any region that may exist on the server, you cannot be added to a second region. 

[df191e00-51f2-4b94-bff7-9ebc354ed987.json.txt](https://github.com/JimiIT92/UniverseGuard2/files/6288851/df191e00-51f2-4b94-bff7-9ebc354ed987.json.txt)

**Comment by JimiIT92** [comment]
That is intentional, as by default a player can only be added to a single region. If you want to be able to add the same player to different regions you have to enable it in the config file. Specifically you need to change the value of the property **unique_regions** and set it to false. Additionally you may want to change the value for **max_regions**, as by default this is set to 10 (meaning that a palyer can't join more than 10 regions)

**Comment by benllben** [comment]
Thank you for your help! I have modified the config for when the server next restarts. 
I believe I got confused by the wording of the comment in the config file as below.
```
# Sets if players can be in more Regions
"unique_regions"=true
```
I was believing it was true that players can be in more regions.

**Comment by JimiIT92** [comment]
Yeah, I might change that to avoid these confusions 😅
