### ISSUE TITLE
Leaf decay flag does not work for Pixelmon leaves

### ISSUE THREAD

**Issue by benllben** [JimiIT92/UniverseGuard2#158]
Setting Leaf Decay to false in the global region stops leaves from breaking as intended, however Pixelmon leaves still decay as usual. Even when inside of a local region with leaf decay turned off, the leaves still decay.

**Comment by JimiIT92** [comment]
Pixelmon blocks in general always had some issues being catched up by the plugin, I think if you scroll the closed issues tab you will find a ton of issues related to that mod 😂 Which version of pixelmon are you using? So I can see what's going on

**Comment by JimiIT92** [comment]
So I tested with the leafdeacy flag set to false and Pixelmon-1.12.2-8.1.2. Unfortunately I don't know the mod too much, so I might be wrong, but I tried with the Grotto Spawner, which spawns in a tree, and with the flag set to false the leaves won't decay when removing the log blocks. So so far it seems that is working, but I might just looked at the wrong thing, so please share more details about which blocks are causing this issue

**Comment by JimiIT92** [comment]
Version 2.35 introduces an improved check on leaves, to make them further compatible with modded ones. Let me know if the issue still occurs after trying this release 😁 You can download it here: https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.35
