### ISSUE TITLE
expand command ignores value

### ISSUE THREAD

**Issue by YorVeX** [JimiIT92/UniverseGuard2#16]
It makes no difference whether I type **/rg expand up 10** or only **/rg expand up** - the region is always expanded to 256 when using the _up_ direction and always to 0 when using the _down_ direction. 

Expansion in any other direction simply does nothing, with or without specifying a value.

I am using version 2.6 for Sponge API 7 with forge-1.12.2-14.23.2.2611 and spongeforge-1.12.2.2611-7.1.0-BETA-2912.

**Comment by JimiIT92** [comment]
Thank you for the report, will look into this issue as soon as possible :)

**Comment by JimiIT92** [comment]
Version 2.7 released! :D 
https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/116
