### ISSUE TITLE
Universe Gaurd overrides plugins spawning armor stands

### ISSUE THREAD

**Issue by benllben** [JimiIT92/UniverseGuard2#160]
I previously use Redprotect but have since moved to UniverseGaurd. Previously we had commands such as /sit which would spawn an invisible armour stand and "sit" the player on it. Also, a pixelmon plugin brings up a selection menu using armour stands. 

However, unless you have the full permissions to the Universe Gaurd plugin, attempting to use these commands in any protected area results in the command failing and the user picking up an armour stand. This allows infinite armour stands being produced while also breaking multiple plugins.

These Armour stands are not being physically placed by a user, hence they should not be stopped.

**Comment by JimiIT92** [comment]
Is the /sit command coming from a plugin? If so please share the name of the plugin, so I can test this out with your exact configuration ;)

**Comment by JimiIT92** [comment]
A potential fix for this issue has been released, among with other fixes. Please let me know if the issue still occur in the new version. If so, please write which plugin is not functioning properly (the one that should spawn armour stands)
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.34
