### ISSUE TITLE
Opening Chests - Universe Guard 2

### ISSUE THREAD

**Issue by RocketManKian** [JimiIT92/UniverseGuard2#161]
Hi there! So I reinstalled this plugin onto my Server and have an issue where player's cannot open Oak Chests on my 1.12.2 Server. So I changed the global config file to allow trapped and normal chests, now they can open every chests except birch. Please help

**Comment by JimiIT92** [comment]
Which mod does these chests come from? Might be an issue about how these blocks are actually registered there, which can lead to them not being seen as chests by the plugin
