### ISSUE TITLE
 crafting table interaction // config 

### ISSUE THREAD

**Issue by thorvi22** [JimiIT92/UniverseGuard2#162]
in the config of the universe guard, in the interaction of the crafting table, when I put false, I can't move the items that are in the inventory and I also can't drop them, it appears that I have permission for this, but only when I change the interaction of the crafting table

**Comment by JimiIT92** [comment]
Version 2.34 has just been released, and it contains a fix for this issue. Check it out here! ;)
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.34
