### ISSUE TITLE
Universe guard 2.33 bug command block

### ISSUE THREAD

**Issue by Suim67** [JimiIT92/UniverseGuard2#167]
I absolutely dont know why, i was using this mod a long time ago and when i upgraded it my command blocks started to stop working.

With this mod inside my server, when i use /fill or /setblock it doesnt work, i see the message ingame and on the console 
 "X blocks placed" but it doesnt appear.
if i /setblock ~ ~1 ~ minecraft:stone ,it won't spawn.

But it can destroy blocks if i /setblock ~ ~1 ~ air 

Im sure it is this mod cause i removed them one per one

Someone got an idea ?

**Comment by Suim67** [comment]
Ok i can add something : the error come from the "place" option in flags.

When its's on true : command blocks can place blocks
When its's on false : command blocks can't place blocks

Is there a way to let command blocks do their job ?

**Comment by Suim67** [comment]
On the 2.22 version of universeguard this bug wasn't there, i just tried

**Comment by JimiIT92** [comment]
So if you manually do a /setblock you can place the block, but the command block doesn't? Looks like is reading the command block as "entity" and checking permissions on it. I'll see what's going on, thank you for the hint on the affected flag

**Comment by JimiIT92** [comment]
Version 2.34 has just been released, and it contains a fix for this issue. Check it out here! ;)
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.34

**Comment by Suim67** [comment]
Thanks a lot ! <3
