### ISSUE TITLE
fluid problems Water, lava and other fluids

### ISSUE THREAD

**Issue by HammerPE** [JimiIT92/UniverseGuard2#168]
It is not allowing me to remove the water from the ground, when I have the waterflow flag set to true. the same goes for lava and other fluids. any solution please?

**Comment by SidewinderDX** [comment]
Duplicate of #153 
JimiIT92 explained the behavior/background of this „issue“ :)

**Comment by JimiIT92** [comment]
This issue has been addressed already. The controversy will be solved in the next release, which will come out this weekend ;)
