### ISSUE TITLE
Feature request: /rg reload

### ISSUE THREAD

**Issue by YorVeX** [JimiIT92/UniverseGuard2#17]
I'd like to have an **/rg reload** command that makes UniverseGuard reload all data from its files.

This way I can mass-edit files using a script and then reload it for the changes to take effect without having to restart the server.

**Comment by JimiIT92** [comment]
That command is already in the plugin, right now is not accessible from console (will be in next version), but typing "/rg reload" it will reload regions from files ;)

**Comment by YorVeX** [comment]
Wow, good to know, thanks! 👍
