### ISSUE TITLE
Projectiles can still do damage

### ISSUE THREAD

**Issue by Dente222** [JimiIT92/UniverseGuard2#170]
Projectile weapons like a bow or modded weapons can still damage player even inside the protected area
skeletons can still attack you too

Can you pleas add flag for that

**Comment by JimiIT92** [comment]
Version 2.34 has just been released, and it contains some changes to how picking/placing fluids works. Check it out here! ;)
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.34

**Comment by JimiIT92** [comment]
Version 2.34 has just been released, and it contains a fix for this issue. Check it out here! ;)
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.34
