### ISSUE TITLE
Blocking placement of modded fluid buckets in regions

### ISSUE THREAD

**Issue by Alydus** [JimiIT92/UniverseGuard2#172]
Is there currently anyway to block the placement of modded fluid buckets? Such as resonant ender from thermal expansion.

Blocking waterflow, lavaflow and otherliquidsflow does not work for this.

**Comment by JimiIT92** [comment]
The `place` flag should block this. I will do some tests with that mod to see what's going on

**Comment by JimiIT92** [comment]
Version 2.35 has just been released, which has a fix for this issue! 😁 You can download it here: https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.35
