### ISSUE TITLE
Separate flag permission?

### ISSUE THREAD

**Issue by baibo233** [JimiIT92/UniverseGuard2#175]
It is a fantastic plugin! But I have some problems.
Sorry if this is not a right place for this question, I have read the wiki many times.
I have trouble in giving separate flag permission to a exact player.
Is there any way to do that?
For example, flag enter&exit, just give `UG.enter.<region>` to them, so they can enter a region named `<region>`.
Thanks!

**Comment by baibo233** [comment]
Sorry, I have read the announce of V3, and learned that the permissions will be implemented in V3.
Thanks, and I am looking forward to the update of v3!

**Comment by JimiIT92** [comment]
Yeah, V3 will have a similar system, where you can specify for each flag the permissions needed to bypass that flag ;)
