### ISSUE TITLE
How i can set PERMISSIONS ?

### ISSUE THREAD

**Issue by Boryenko** [JimiIT92/UniverseGuard2#176]
I'm using Luck Perms. When i've started configuring permissions i understood that there is no information about permissins for UniverseGuard. Where I can get the list of perms?

**Comment by RobertCUH** [comment]
Same question here brother

**Comment by JimiIT92** [comment]
There are currently 2 permissions you can set: all (which basically make who has that bypassing all protections) and region (which makes so who has this permission will bypass any region specific permission, but still be subject to global restrictions). You can find them in the wiki here: https://github.com/JimiIT92/UniverseGuard2/wiki/config#permissions
