### ISSUE TITLE
Unable to get "/rg add" to work

### ISSUE THREAD

**Issue by YorVeX** [JimiIT92/UniverseGuard2#18]
I can't figure out how to get **/rg add** to work. What I want is to add the user n_ib to the members of the region "Vexanos". Here's what I tried (in exactly that order) and what the response was:

`/rg add owner n_ib Vexanos`
> No values matching pattern 'n_ib' present for name!
> add owner n_ib Vexanos
> _________^
> Usage: /rg add <role> <name> [<region>]

`/rg add member n_ib Vexanos`
> No values matching pattern 'n_ib' present for name!
> add member n_ib Vexanos
> ___________^
> Usage: /rg add <role> <name> [<region>]

`/rg edit Vexanos`
> Pending region updated!
> Editing region: Vexanos

`/rg add owner n_ib`
> No values matching pattern 'n_ib' present for name!
> add owner n_ib
> _________^
> Usage: /rg add <role> <name> [<region>]

It doesn't say that in the documentation but maybe it doesn't work for users which aren't connected to the server right now (which would be bad IMHO) so I tried again with myself:

`/rg add owner YorVeX`
> The player is already a member of a region

But I am not, this is the first time I am trying to add myself to a region. Also I checked all region json files on the server and none of them is listing any member at all - it's always an empty JSON array.

What am I missing?

BTW: does that message mean any player can only be added as member of one region? That would be really bad and basically mean I need to find a different plugin. I plan to add players both to a bigger and shared region and to also give each player a smaller region solely for him.

**Comment by YorVeX** [comment]
I restarted the server and then tried:
`/rg add member YorVeX Vexanos`
> [01:58:33] [Server thread/INFO]: Universe Guard 2: Exception saving region. See log for details

Now that's a different one. Where does it write that log to? I checked the Minecraft "logs" folder but it doesn't have any line that matches or is close to the above timestamp, also no exception in general.

**Comment by JimiIT92** [comment]
The command syntax of last try is correct, however there could be a bug in this command due to api7 porting. For the membership, it can be changed so players can be in member of multiple regions (it's an easy change)

**Comment by YorVeX** [comment]
It would be nice if you could change it, I created #19 for that.

**Comment by JimiIT92** [comment]
Version 2.7 released! :D 
https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/116
