### ISSUE TITLE
Feature request: add members to more than one region

### ISSUE THREAD

**Issue by YorVeX** [JimiIT92/UniverseGuard2#19]
Right now when trying to add a player to a new region who is already member of another region it fails with the message: _The player is already a member of a region_

Please make it possible to add players to more than one region. This shouldn't cause any logical issues because UG2 already has a priority system that defines which region is currently relevant to a player.

**Comment by JimiIT92** [comment]
Version 2.7 released! :D 
https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/116

**Comment by XBase-xOR** [comment]
Doesn't seem to work, I still get the message *The player is already a member of a region* when I try to add myself to more than one region.

**Comment by JimiIT92** [comment]
Have you set to false the field "unique_regions" in the config file?

**Comment by YorVeX** [comment]
unique_regions is enabled. We had a situation where another mod on my server was unable to add someone as a member of a region getting the error message mentioned here. Then I tried exactly the same command he has used and I could add the user. Maybe this is a permission problem or something else. I will report back when I find out more details.
