### ISSUE TITLE
1.12.2 error

### ISSUE THREAD

**Issue by tryolivier** [JimiIT92/UniverseGuard2#2]
hello

I use UniverseGuard-2.1.jar https://mega.nz/#!MZ8nlarC!v95w-Iub5xfSObE-MRYSfiTC0O-LLLW4GGjOI05NhlA

/region do : 
https://paste.md-5.net/homavaqoho.rb

/rg do 
https://paste.md-5.net/godupofeqi.rb

to create region only /rg or /rg create ??

thanks for the plugin =)

good day =)

**Comment by JimiIT92** [comment]
This is a well known issue with 1.12. The ItemEnchantment class is gone in API7 (wich MC1.12 uses i believe). An API7 version is in development and will be released very soon, so stay tuned for updates ;) By the way to create a region you don't have to type a command, just use /rg to get the Region selector and then select the Region bounds using left click and right click. More details can be found in the wiki [here](https://github.com/JimiIT92/UniverseGuard2/wiki)

**Comment by unstablecraft** [comment]
any news on this ??

**Comment by tryolivier** [comment]
No we have to wait 1.12.2 version

:)

**Comment by unstablecraft** [comment]
oke thanks was looking for a new protection plugins since redprotect is bugged to the max

**Comment by JimiIT92** [comment]
SpongeAPI 7 (for MC-1.12.2) has been released today, so in a day or two i'll end up the API7 version of the plugin and this error (as well as other compatibilities errors) will be fixed ;)

**Comment by unstablecraft** [comment]
thanks a lot for your response

**Comment by tryolivier** [comment]
Thanks for the reply

I don't see today update 

In https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661

It says 1.12.2 api7 will be for soon

But thanks :)

Thanks have a nice day!

Thanks for the plugin and the help 

Happy new year!!

**Comment by JimiIT92** [comment]
That's because on December31 API7 has been released, not the API7 version of the plugin. That will be released soon, when all the updates and tests are done with the new APIs ;)

**Comment by unstablecraft** [comment]
please tell me your done :D

**Comment by JimiIT92** [comment]
Almost, i'm having issues with some flags wich cause is an Entity. Some EntitySource classes has been removed or merged with others, so i'm now finding where are these in API7 and testing everything out. If everything goes well the new version will be done within the next week ;)

**Comment by baipgej222** [comment]
go go go

**Comment by unstablecraft** [comment]
thats not very nice bro he's busy so be patient

**Comment by JimiIT92** [comment]
Ahah, don't worry, i understand this is a long-waited feature, i want it to be out soon too. But API7 has changed how entity-related events are handled. For instance, the EntitySpawnCause is gone (or perhaps i didn't find a substitute), so any event that uses that class has to be rewrite :/

**Comment by JimiIT92** [comment]
Released API7 version for MC-1.12.2. Read more at [https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/87](https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/87)
