### ISSUE TITLE
Weird Error

### ISSUE THREAD

**Issue by ReaperAngels** [JimiIT92/UniverseGuard2#22]
#21 
Hi, lovely plugin, I love it. 
But, it worked for awhile quite nicely. Then I loaded MobController (Forge mod) and UniverseGuard started showing an error.
java.lang.NullPointerException: null
        at com.universeguard.utils.RegionUtils.load(RegionUtils.java:145) ~[Regi
onUtils.class:?]
        at com.universeguard.UniverseGuard.onGameStart(UniverseGuard.java:160) ~
[UniverseGuard.class:?]
        at org.spongepowered.common.event.listener.GameStartedServerEventListene
r_UniverseGuard_onGameStart9.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredLi
stener.java:95) ~[RegisteredListener.class:1.12.2-2611-7.1.0-BETA-2963]

I of course removed MobController, but still get the same error. On checking the source, I saw line 145 is actually a comment. 
I'm going to remove ALL the plugins and mods, and then start adding them again one by one. 

Will let you know the results

OK, removed all and started to add one by one. No problems until I added UniverseGuard. Same error. 
To be honest, I'm thinking the problem is NOT with your plugin. It's SpongeForge that generates the error. Attaching log for your info.
[fml-junk-earlystartup.log](https://github.com/JimiIT92/UniverseGuard2/files/1848517/fml-junk-earlystartup.log)

You can close this. It was a json formatting error.

**Comment by JimiIT92** [comment]
I'm glad you solved this by yourself, but i'm curious to know what the error was so i can see if i prevent it in the future (if it's related to a plugin file) :)

**Comment by JimiIT92** [comment]
That's strange because i generate the Json files with the Gson library :/
