### ISSUE TITLE
Added features?

### ISSUE THREAD

**Issue by ReaperAngels** [JimiIT92/UniverseGuard2#23]
Hi, I wonder if you could please add "Enter Message" and "Exit Message"? It will be handy for players to know when they are no longer protected by the spawn. 
How does the mob-spawning work? Does your plugin stop mobs from spawning in a region?

Looking forward to hearing from you!

**Comment by JimiIT92** [comment]
The enter and exit messages are already in the plugin. You can set these while editing a region using the /rg greeting and /rg farewell commands. As for the mob spawning: yes, it prevents a specific mob (or all of a kind you can specify) to spawn in that region (this can be applied to a global region too). Keep in mind that the mob can still spawn in a region near this, and so it can enter the region where he can't spawn

**Comment by ReaperAngels** [comment]
That's great. But not sure how I missed that. I was specifically looking for that. Anyway, thank you!
