### ISSUE TITLE
PvE Buggy

### ISSUE THREAD

**Issue by DibDibs** [JimiIT92/UniverseGuard2#25]
A region where mobs cannot spawn, but PvE is enabled does not allow members to attack mobs.
![image](https://user-images.githubusercontent.com/8533154/38372259-4b26f56c-38e6-11e8-9b10-5b8d4385ff02.png)
_Image showing that I can't attack mobs in my region._

**Comment by JimiIT92** [comment]
Thanks for the report, will look into that ;)

**Comment by JimiIT92** [comment]
Fixed in the next release ;) Check out the Sponge page to see when it's released ;)
