### ISSUE TITLE
Can't drop items on local regions

### ISSUE THREAD

**Issue by chistian95** [JimiIT92/UniverseGuard2#27]
Even if you set the "itemdrop" flag to true, you can't drop items on any local regions.

Tried with sponge 7.1.0 and UniverseGuard 2.7 for Minecraft 1.12.2

**Comment by JimiIT92** [comment]
Thank you for the report, i am looking already into this issue ;)

**Comment by JimiIT92** [comment]
Fixed in version 2.8! Check the Sponge page soon to get more details about ;) 
https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/
