### ISSUE TITLE
Suggestion: Crop trampling

### ISSUE THREAD

**Issue by ReaperAngels** [JimiIT92/UniverseGuard2#28]
Hi,
Can you perhaps add a flag for crop trampling for both players and mobs? It seems to be the only real flag missing.

Thank you!

**Comment by JimiIT92** [comment]
At the moment you can prevent crops from breaking by just setting the destroy flag to false. A proper flag just for crops will be added later ;)

**Comment by ReaperAngels** [comment]
I was thinking along the lines of a global flag. It's not really feasible to make a region for every player's crops. But thank you, I await it with great anticipation :grinning:

**Comment by JimiIT92** [comment]
I tried to add this flag in the new version 2.8, but it turned out is not as easy at it could seem. So i reminded this to the next release so i can get more time to make it work ;)

**Comment by JimiIT92** [comment]
Flag added in version 2.9 :D Check the post on the Sponge topic to download it :D 
[https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/143](https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/143)
