### ISSUE TITLE
Region Flags

### ISSUE THREAD

**Issue by gaz8203** [JimiIT92/UniverseGuard2#29]
Hi, I cant seem to get the mobspawn disallow flag to work.
I have tried every variation i can think of, including rg flag mobspawn disallow
always get the following error message 
![image](https://user-images.githubusercontent.com/38543873/39022459-92bc1dce-442d-11e8-8300-f5861403e24b.png)

Please can you tell me the correct way to write the command?
Thanks

**Comment by JimiIT92** [comment]
The correct command for your case is
/rg flag mobspawn minecraft:creeper false
The syntax is
/rg flag mobsapwn <mod-id>:<mob-name> <true | false>. Modid stands for wich part of the game adds the mob, so in case of a vanilla mob is "minecraft", in case of a mob from a mod it's the mod-id. In a future release this will be changed so the mod id will no longer be required, at least for vanilla mobs ;)

**Comment by gaz8203** [comment]
Perfect, that works. Thanks so much!
