### ISSUE TITLE
Itemframes can be broken

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [JimiIT92/UniverseGuard2#3]
Itemframes can just easily be broken with whatever flag is on.

**Comment by JimiIT92** [comment]
Will look into this issue as soon as possible ;)

**Comment by JimiIT92** [comment]
Tested and fixed for the next release ;)

**Comment by JimiIT92** [comment]
Version 2.6 released! Read more at [https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/87](https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/87)
