### ISSUE TITLE
Thrown items vanishing in build deny areas

### ISSUE THREAD

**Issue by DragaoNimhe** [JimiIT92/UniverseGuard2#30]
As the title states, when our users throw an item in an area that is protected with the flag build deny, the item vanishes and they are told they do not have perms to do that. The itemdrop flag is set to true in all cases. This is very upsetting as our players will certainly attempt to trade items with each other using /spawn, as well as may accidentally throw very valuable items, only to lose them forever. Any help with this issue would be greatly appreciated, if you need any more information I would be happy to provide it.

**Comment by JimiIT92** [comment]
Could be some interference from the build flag with the entity of the item dropped being spawned, will look into this as many users are reporting this bug with the drops  ;)

**Comment by CathalCraft** [comment]
Same issue on my server. Very annoying for players trying to trade at spawn.

**Comment by JimiIT92** [comment]
Fixed in version 2.8! Check the Sponge page soon to get more details about ;) 
https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/
