### ISSUE TITLE
Player getting permission denied message when killing mobs in region with pvp flag disabled.

### ISSUE THREAD

**Issue by seisatsu** [JimiIT92/UniverseGuard2#34]
In a global region (no local region) with the pvp flag set to false, a player is getting a message that they "aren't allowed to do that" every time they kill (not just attack) a mob which was spawned from a mob spawner block. Re-enabling the pvp flag removes the message. Strangely, mobs which spawned naturally (not from a spawner block) are not producing the message. The user also reports that spawner block mobs can't hurt them. I am a little stumped about this situation.

**Comment by JimiIT92** [comment]
Will look into this issue ;)

**Comment by JimiIT92** [comment]
Were the mobs vanilla mobs or they comes from a  mod (and if so wich)? Because i've just tested on version 2.8, API7, and it seems to works as intended :/

**Comment by seisatsu** [comment]
They were vanilla mobs. Honestly this may be a hopeless case, because other users haven't reported such an issue, just this one. It may just be one of those bugs with such an obscure trigger that you aren't going to find anything. Keep an eye out and I'll let you know if any new information surfaces.

**Comment by JimiIT92** [comment]
Thanks and yes, this sounds like a unique case and unfortunately is hard to test. Try updating to version 2.8 and see if it fixes this ;)
