### ISSUE TITLE
Purchasable Regions

### ISSUE THREAD

**Issue by spruill7716** [JimiIT92/UniverseGuard2#36]
Used to have a plugin on Spigot called AreaShop that allowed defined regions to be purchased through a sign format or command. Since this is the only region based plugin working with sponge, I figured I'd make a suggestion. Allow regions to be bought/rented and automatically add the player who purchased the lot to the region so they can build and interact.

**Comment by JimiIT92** [comment]
This is a great suggestion, as it will also let me introduce a proper distinction between region owners and region members, so i'll definitively add it in a next version ;)

**Comment by JimiIT92** [comment]
Added in version 2.12 for Minecraft 1.12.2 only. More infos on the official sponge post [here](https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/158) :D
