### ISSUE TITLE
Users cannot use a lighter in a region they do not own, even if the lighter permission is enabled.

### ISSUE THREAD

**Issue by seisatsu** [JimiIT92/UniverseGuard2#38]
I had a protected region where I wanted users to be able to use a lighter in a certain area to light a netherrack block that would be read by an observer block as part of a puzzle, but even though the lighter permission was enabled in the region, users were unable to use a lighter on the block. Which other permission is blocking them from doing so? Does this count as "placing" a block? Could this behavior be changed?

**Comment by JimiIT92** [comment]
Yes, it sounds like the placing flag is also blocking the fire placing. Will look into this issue and will fix it for the next version ;)
