### ISSUE TITLE
Feature Request:  Additional Flags

### ISSUE THREAD

**Issue by Trellinane** [JimiIT92/UniverseGuard2#40]
Hello.  I am just starting to use the plugin as I start to set up a new sponge server and so far it appears to do the job quite nicely.  One request I have is whether you could add some additional flags to the simple flags.  Specifically what I need is a flag that could apply potion effects on entering a region and have them start to dissipate on leaving a region (or be removed immediately if easier).  One idea I had in mind was to create say like an irradiated zone that would apply some nasty effects without proper protection.

There is a Spigot plugin called Worldguard Extra Flags that appears spot on if the assist in providing direction and/or inspiration.  

Thank you very much.

**Comment by JimiIT92** [comment]
Sounds like a good idea to create some special regions on a server, i'll see if i can add this in the next release ;)

**Comment by JimiIT92** [comment]
Added in version 2.11 for Minecraft 1.12.2 only. Forgot to post it here too 😅  More infos on the official sponge post [here](https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/158) :D
