### ISSUE TITLE
North, South, East, West for /rg expand

### ISSUE THREAD

**Issue by seisatsu** [JimiIT92/UniverseGuard2#41]
Can you add North, South, East, and West as aliases for Back, Front, Right, and Left when using /rg expand and any other commands which take a direction as an argument? It's more intuitive when checking your facing with F3, and it's consistent with WorldEdit. I always have to remind myself that Back is North, which doesn't make much sense to me. I think some people including myself would be more comfortable with cardinal directions, and it shouldn't take much effort to add.

**Comment by JimiIT92** [comment]
Will be added in next version ;) Make sure to use the API7 version since it will be added just there ;)

**Comment by JimiIT92** [comment]
Added in version 2.12 for Minecraft 1.12.2 only. More infos on the official sponge post [https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/158](here) :D
