### ISSUE TITLE
Feature Request - ClaimBlock

### ISSUE THREAD

**Issue by hellbringer616** [JimiIT92/UniverseGuard2#42]
A block that when you place it adds a cubed region of x,y,z dimension.

Settings:
Admin can define which block functions as the claim block
Admin can predefine flags the ClaimBlock has when placed by anyone.
Admin can predefine the x,y,z dimensions

**Comment by JimiIT92** [comment]
This will make much easier the Region template feature i'm working on. Basically you will be able to define  a template for a Region and then "store" that template in a block that only players with a given permission that you decide can place

**Comment by JimiIT92** [comment]
Region templates added in version 2.13! Check it out! :D [https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/162](https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/162)
