### ISSUE TITLE
API for using UniverseGuard2 in other plugins

### ISSUE THREAD

**Issue by randombyte-developer** [JimiIT92/UniverseGuard2#43]
A feature request: https://forums.spongepowered.org/t/claimblocks-protect-land-by-placing-claim-blocks/19361/11?u=randombyte

ClaimBlocks needs access to the regions(create, edit, delete) of UniverseGuard and would have to assign owners. Is this easily possible and is that kind of a stable API?

**Comment by JimiIT92** [comment]
Right now there is no official "API" for UniverseGuard. At some point there will be, but for now you can try to run different commands to know in wich region the player currently is and add it to the Region, or (this is a really really bad solution but could works) you can import the project as an external library into your and so you can access the plugin methods from your project

**Comment by JimiIT92** [comment]
A proper way to extend the plugin from other plugins (like for example WorldEdit does) will be added in the next major version (Version 3) wich is in development
