### ISSUE TITLE
Issue with permissions 

### ISSUE THREAD

**Issue by wormzjl** [JimiIT92/UniverseGuard2#45]
I've been using 2.13 version of this plugin on spongeforge and I've given myself universeguard.all and universeguard.* permnode.
However whenever I try to use the /rg command it says I don't have necessary permissions...

**Comment by JimiIT92** [comment]
The universeguard.* permission is not handled by the plugin, you should use the universeguard.all permission. However if you had both of them than the all permission should be handled, so i'll look into this issue and maybe add an alias for the all permission so you can use both all or * ;)
