### ISSUE TITLE
Block break issue

### ISSUE THREAD

**Issue by ncbabe** [JimiIT92/UniverseGuard2#47]
Player on sponge server can manage to get block drops after continuously mining permission-protected block several times. The block itself breaks -> gives drops -> and reappear.

**Comment by JimiIT92** [comment]
Will look into this as soon as possible ;)

**Comment by JimiIT92** [comment]
Sorry for being late, but i looked into this issue, spent around 10 mins breaking the same block (a grass block) in creative and then other 10 mins in survival. Unfortunately i haven't got this bug, so i ask you: wich block you were breaking when the bug appear? Also can you send me the json file associated with the region, as it could be some flags conflict?
