### ISSUE TITLE
[1.12.2] Could not pass MoveEntityEvent (Moved from https://github.com/JimiIT92/UniverseGuard/issues/18)

### ISSUE THREAD

**Issue by JimiIT92** [JimiIT92/UniverseGuard2#49]
[Server] Server thread/ERROR [Sponge]: Could not pass MoveEntityEvent$Impl to Plugin{id=universeguard, name=Universe Guard 2, version=2.14, description=An easy to use world protection plugin for Sponge, authors=[JimiIT92, Brycey92, eheimer], source=/./mods/plugins/UniverseGuard-2.14-1.12.2.jar}

API VERSION: 7.1.0-SNAPSHOT-43d8496
Sponge VERSION: 1.12.2-2705-7.1.0-BETA-3136

**Comment by Rsslone** [comment]
This issue occurs when you remove the region for the dim (world).

**Comment by Rsslone** [comment]
```
28.07 14:39:53 [Server] Server thread/ERROR [Sponge]: Could not pass ChangeBlockEvent$Pre$Impl to Plugin{id=universeguard, name=Universe Guard 2, version=2.14, description=An easy to use world protection plugin for Sponge, authors=[JimiIT92, Brycey92, eheimer], source=/./mods/plugins/UniverseGuard-2.14-1.12.2.jar}
28.07 14:39:53 [Server] INFO java.lang.NullPointerException: null
28.07 14:39:53 [Server] INFO at ic2.core.block.BlockTileEntity.getTe(BlockTileEntity.java:929) ~[BlockTileEntity.class:?]
28.07 14:39:53 [Server] INFO at ic2.core.block.BlockTileEntity.func_176195_g(BlockTileEntity.java:857) ~[BlockTileEntity.class:?]
28.07 14:39:53 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185887_b(BlockStateContainer.java:403) ~[awu$a.class:?]
28.07 14:39:53 [Server] INFO at org.spongepowered.common.data.property.store.block.UnbreakablePropertyStore.getForBlock(UnbreakablePropertyStore.java:47) ~[UnbreakablePropertyStore.class:1.12.2-2705-7.1.0-BETA-3136]
28.07 14:39:53 [Server] INFO at org.spongepowered.common.data.property.store.common.AbstractBlockPropertyStore.getFor(AbstractBlockPropertyStore.java:88) ~[AbstractBlockPropertyStore.class:1.12.2-2705-7.1.0-BETA-3136]
28.07 14:39:53 [Server] INFO at org.spongepowered.common.data.property.PropertyStoreDelegate.getFor(PropertyStoreDelegate.java:48) ~[PropertyStoreDelegate.class:1.12.2-2705-7.1.0-BETA-3136]
28.07 14:39:53 [Server] INFO at org.spongepowered.common.data.property.SpongePropertyRegistry.getPropertiesFor(SpongePropertyRegistry.java:91) ~[SpongePropertyRegistry.class:1.12.2-2705-7.1.0-BETA-3136]
28.07 14:39:53 [Server] INFO at net.minecraft.block.Block.populateSpongeProperties(Block.java:2898) ~[aow.class:?]
28.07 14:39:53 [Server] INFO at net.minecraft.block.Block.getProperties(Block.java:2892) ~[aow.class:?]
28.07 14:39:53 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.getSpongeInternalProperties(BlockStateContainer.java:862) ~[awu$a.class:?]
28.07 14:39:53 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.getProperty(BlockStateContainer.java:852) ~[awu$a.class:?]
28.07 14:39:53 [Server] INFO at com.universeguard.event.flags.FlagWaterFlowListener.onWaterFlow(FlagWaterFlowListener.java:43) ~[FlagWaterFlowListener.class:?]
28.07 14:39:53 [Server] INFO at org.spongepowered.common.event.listener.PreListener_FlagWaterFlowListener_onWaterFlow152.handle(Unknown Source) ~[?:?]
28.07 14:39:53 [Server] INFO at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3136]
```

**Comment by JimiIT92** [comment]
Sorry for being late, but can you send me via PM the json file of the Region? Because i've tried to set a Region with the waterflow flag to false and then remove it from the world dimension but there was no error message, so there could be a specific configuration that is causing this issue

**Comment by Rsslone** [comment]
Honestly I've been using the plugin more and I don't see the spam anymore. I've removed a couple mods that had dims from my modpack and at some point the spam stopped. I'll send the files to you anyways if it will help.

**Comment by Rsslone** [comment]
Where should I PM you at?

**Comment by JimiIT92** [comment]
For some reason i always thought there was PM on GitHub as well. Turned out there isn't 😅 Send me an email at jimiit92@gmail.com

**Comment by mwitt-secret** [comment]
It appears on the first load of a level then dissapears after a while

All I had to do was unpack something like lockwood manor
(http://www.mediafire.com/file/fd293qn5y915c45/Lockwood+Manor.rar)

then /world create -i lockwood

walking through the fresh world spams the above. 

After you go through the world for a bit, it stops spamming.

**Comment by JimiIT92** [comment]
Looking at the stacktrace it seems that the error might be caused by some missing checks in the waterflow flag. I've added them now, walked into new worlds for about an hour an get no errors as well. So it really might be that the cause. Let me know if this error still occur in version 2.16 when it will be released later today ;)

**Comment by JimiIT92** [comment]
Version 2.16 released! Check it here ;) [https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/177](https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/177)

**Comment by InnuendoSA** [comment]
Hi.
I still have this problem.
Every Dimensions I create with "Just Enough Dimensions" have this error:
https://pastebin.com/EQwm1rk1
It happens every time I move. 
The error in the paste bin was from taping "W" one time. 
If I move my mouse its 1 mil. times worse in the console.

Versions 2.15 and 2.16 did not make a file under "config\universeguard\globals" for any new Dimensions.

Lastly I get "Universe Guard 2: false" in the console now and then...

**Comment by JimiIT92** [comment]
The files for new dimensions should be created on the server start, since i don't know if there is any hook that tells sponge "a new dimension has been created". I'll see if i can made it so the files are created "in real time". That being said, i'll download that mod and see what is causing the error and also the "false" spam ;)

**Comment by InnuendoSA** [comment]
Thanks you are the Man!

**Comment by XclusivVv** [comment]
Hi, i'm still having this issue on 2.17 (https://pastebin.com/DY7UQuUc) any idea what I am to do about it?
The error started happening when I already had 1 region open for edit mode using /rg edit but one of the players was having an issue in their own region, so I edited their region at the same time by typing the commands into chat.

Was the error caused by me editing 2 regions simultaneously? How can I stop it from spamming the console?

**Comment by sfxworks** [comment]
This is still occurring
This is spamming the log
```
[03:38:48] [Server thread/ERROR] [Sponge]: Could not pass MoveEntityEvent$Impl to Plugin{id=universeguard, name=Universe Guard 2, version=2.17, description=An easy to use world protection plugin for Sponge, authors=[JimiIT92, Brycey92, eheimer], source=/server/./mods/plugins/UniverseGuard-2.17.jar}
java.lang.ClassCastException: null
```

**Comment by austin4195** [comment]
I am seeing this error as well
