### ISSUE TITLE
lagg issues bounded to universeguard

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [JimiIT92/UniverseGuard2#5]
It seems be the reason my server tps to go down 

https://timings.aikar.co/?id=d18847d2f73b40458a54ab70b5ebc0ef#timings (right after reboot)

https://timings.aikar.co/?id=3716b2ad29a048568456cb6c81654827 (Little after that)

**Comment by JimiIT92** [comment]
Thank you for the report. I know some events are causing lag and i'm already working on a fix ;)

**Comment by Brycey92** [comment]
Related to #4

**Comment by JimiIT92** [comment]
Region cache added in the next version ;)

**Comment by JimiIT92** [comment]
Version 2.6, with Region cache, released! Read more at: [https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/87](https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/87)
