### ISSUE TITLE
No damage

### ISSUE THREAD

**Issue by SilverRu9** [JimiIT92/UniverseGuard2#57]
I don't recieve any damage on local or global regions. Mobdamage is ON. Lava, falling, mobs... even "/kill" not working. But if I delete global region, this problem disappear. (UniverseGuard 2.17)

**Comment by Bnod23** [comment]
check your flags via the config file. its one of the ones in the global file. they are long. see if mob damage is on in there. if not then change it in the file save and reload the plugin /rg reload
