### ISSUE TITLE
Error after reinstallation

### ISSUE THREAD

**Issue by dodulu** [JimiIT92/UniverseGuard2#59]
[Sponge]: Failed to create handler for public void com.universeguard.event.flags.FlagInteractListener.onItemCraft(org.spongepowered.api.event.item.inventory.ClickInventoryEvent,org.spongepowered.api.entity.living.player.Player,org.spongepowered.api.item.inventory.Inventory) on class com.universeguard.event.flags.FlagInteractListenercom.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Method public abstract org.spongepowered.api.item.inventory.Container org.spongepowered.api.event.item.inventory.TargetContainerEvent.getTargetInventory() does not return the correct type. Expected: org.spongepowered.api.item.inventory.Inventory Found: org.spongepowered.api.item.inventory.Containerat com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[minecraft_server.1.12.2.jar:?]at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[minecraft_server.1.12.2.jar:?]at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[minecraft_server.1.12.2.jar:?]at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[minecraft_server.1.12.2.jar:?]at org.spongepowered.common.event.ClassEventListenerFactory.create(ClassEventListenerFactory.java:96) ~[ClassEventListenerFactory.class:1.12.2-2768-7.1.4]at org.spongepowered.common.event.SpongeEventManager.registerListener(SpongeEventManager.java:253) [SpongeEventManager.class:1.12.2-2768-7.1.4]at org.spongepowered.common.event.SpongeEventManager.registerListeners(SpongeEventManager.java:311) [SpongeEventManager.class:1.12.2-2768-7.1.4]at com.universeguard.utils.EventUtils.registerEvent(EventUtils.java:38) [EventUtils.class:?]at com.universeguard.UniverseGuard.registerEvents(UniverseGuard.java:444) [UniverseGuard.class:?]at com.universeguard.UniverseGuard.onInit(UniverseGuard.java:200) [UniverseGuard.class:?]at org.spongepowered.common.event.listener.GameInitializationEventListener_UniverseGuard_onInit11.handle(Unknown Source) [?:?]at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) [RegisteredListener.class:1.12.2-2768-7.1.4]at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2768-7.1.4]at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:1.12.2-2768-7.1.4]at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2768-7.1.4]at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:248) [SpongeImpl.class:1.12.2-2768-7.1.4]at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:272) [SpongeMod.class:1.12.2-2768-7.1.4]at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) [LoadController.class:?]at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) [LoadController.class:?]at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) [LoadController.class:?]at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744) [Loader.class:?]at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Method public abstract org.spongepowered.api.item.inventory.Container org.spongepowered.api.event.item.inventory.TargetContainerEvent.getTargetInventory() does not return the correct type. Expected: org.spongepowered.api.item.inventory.Inventory Found: org.spongepowered.api.item.inventory.Containerat com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[minecraft_server.1.12.2.jar:?]at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[minecraft_server.1.12.2.jar:?]at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[minecraft_server.1.12.2.jar:?]at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[minecraft_server.1.12.2.jar:?]at org.spongepowered.common.event.filter.FilterFactory.createFilter(FilterFactory.java:60) ~[spongeforge-1.12.2-2768-7.1.4.jar:1.12.2-2768-7.1.4]at org.spongepowered.common.event.ClassEventListenerFactory.createClass(ClassEventListenerFactory.java:106) ~[spongeforge-1.12.2-2768-7.1.4.jar:1.12.2-2768-7.1.4]at org.spongepowered.common.event.ClassEventListenerFactory$1.load(ClassEventListenerFactory.java:79) ~[spongeforge-1.12.2-2768-7.1.4.jar:1.12.2-2768-7.1.4]at org.spongepowered.common.event.ClassEventListenerFactory$1.load(ClassEventListenerFactory.java:75) ~[spongeforge-1.12.2-2768-7.1.4.jar:1.12.2-2768-7.1.4]at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[minecraft_server.1.12.2.jar:?]at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[minecraft_server.1.12.2.jar:?]at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[minecraft_server.1.12.2.jar:?]at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[minecraft_server.1.12.2.jar:?]... 48 moreCaused by: java.lang.IllegalArgumentException: Method public abstract org.spongepowered.api.item.inventory.Container org.spongepowered.api.event.item.inventory.TargetContainerEvent.getTargetInventory() does not return the correct type. Expected: org.spongepowered.api.item.inventory.Inventory Found: org.spongepowered.api.item.inventory.Containerat org.spongepowered.common.event.filter.delegate.GetterFilterSourceDelegate.write(GetterFilterSourceDelegate.java:79) ~[spongeforge-1.12.2-2768-7.1.4.jar:1.12.2-2768-7.1.4]at org.spongepowered.common.event.filter.FilterGenerator.generateClass(FilterGenerator.java:189) ~[spongeforge-1.12.2-2768-7.1.4.jar:1.12.2-2768-7.1.4]at org.spongepowered.common.event.filter.FilterFactory.createClass(FilterFactory.java:68) ~[spongeforge-1.12.2-2768-7.1.4.jar:1.12.2-2768-7.1.4]at org.spongepowered.common.event.filter.FilterFactory$1.load(FilterFactory.java:47) ~[spongeforge-1.12.2-2768-7.1.4.jar:1.12.2-2768-7.1.4]at org.spongepowered.common.event.filter.FilterFactory$1.load(FilterFactory.java:43) ~[spongeforge-1.12.2-2768-7.1.4.jar:1.12.2-2768-7.1.4]at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[minecraft_server.1.12.2.jar:?]at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[minecraft_server.1.12.2.jar:?]at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[minecraft_server.1.12.2.jar:?]at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[minecraft_server.1.12.2.jar:?]at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[minecraft_server.1.12.2.jar:?]at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[minecraft_server.1.12.2.jar:?]at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[minecraft_server.1.12.2.jar:?]at org.spongepowered.common.event.filter.FilterFactory.createFilter(FilterFactory.java:60) ~[spongeforge-1.12.2-2768-7.1.4.jar:1.12.2-2768-7.1.4]at org.spongepowered.common.event.ClassEventListenerFactory.createClass(ClassEventListenerFactory.java:106) ~[spongeforge-1.12.2-2768-7.1.4.jar:1.12.2-2768-7.1.4]at org.spongepowered.common.event.ClassEventListenerFactory$1.load(ClassEventListenerFactory.java:79) ~[spongeforge-1.12.2-2768-7.1.4.jar:1.12.2-2768-7.1.4]at org.spongepowered.common.event.ClassEventListenerFactory$1.load(ClassEventListenerFactory.java:75) ~[spongeforge-1.12.2-2768-7.1.4.jar:1.12.2-2768-7.1.4]at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[minecraft_server.1.12.2.jar:?]at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[minecraft_server.1.12.2.jar:?]at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[minecraft_server.1.12.2.jar:?]at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[minecraft_server.1.12.2.jar:?]... 48 more

**Comment by dodulu** [comment]
sorry if obvious but im beginer

**Comment by JimiIT92** [comment]
Try using the 7.1.0 version of Sponge. It looks like something in inventory management has been change in version 7.1.4

**Comment by dodulu** [comment]
meme probleme
bizarrement en local aucun souci sur le server par contre sa ne marche pas
