### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by kenijey** [JimiIT92/UniverseGuard2#6]
It doesn't work on Minecraft 1.12.2 Forge 2604 server with Sponge API 7.1.0 2848.
if i type /region it errors. please help...

**Comment by JimiIT92** [comment]
That's because this version has been built using API6. API7 version is in development and will come soon ;)

**Comment by kenijey** [comment]
oh... but in the UniverseGuard sponge page it says "This plugin was tested with 1.10.2 ; 1.11.2 and 1.12 minecraft version with sponge API 5 ; 6 and 7." isnt it for this plugin?

**Comment by JimiIT92** [comment]
That was the page for the old version of the plugin, this new version is completely different ad also API7 has changed a lot since that  post (so i guess that version no longer works with API7)

**Comment by JimiIT92** [comment]
Released API7 version for MC-1.12.2. Read more at [https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/87](https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/87)
