### ISSUE TITLE
Issue regarding fire

### ISSUE THREAD

**Issue by fancyabum** [JimiIT92/UniverseGuard2#61]
No matter what you specify to be blocked (even setting all flags to false) there is an issue regarding fire. Firecharges still create fire in an area no matter what the flags set are, this issue is not only present with fire charges as weapons from other mods can also create fire in an area.

**Comment by JimiIT92** [comment]
Fixed in version 2.18 :)
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.18
