### ISSUE TITLE
UniverseGuard 2 is blocking ChangeBlockEvents from reaching my plugin.

### ISSUE THREAD

**Issue by codeHusky** [JimiIT92/UniverseGuard2#63]
Hi, I'm the developer of Husky Crates.

I recently received a report of a player being unable to place crates. This boiled down to a conflict between our plugins, specifically with your plugin preventing mine from receiving a block place event, even if the block was successfully placed by an admin.

This shouldn't be happening, and it's important that this gets fixed to prevent user confusion.

**Comment by JimiIT92** [comment]
I'll download your plugin to see what is causing the issue and fix it for the next release ;)

**Comment by JimiIT92** [comment]
Hi, i've tested your plugin while developing latest version but unfortunately i can't find any issue, i was able to place and use the crates as non admin player while universe guard was running. Keep in mind that in the latest version some code related to the place and destroy flags has changed, so maybe as a side effect this has fixed the crate issue. Let me know if the issue still happens using the latest version wich can be found here
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.18
