### ISSUE TITLE
Where to find all permissions?!

### ISSUE THREAD

**Issue by SirMech1995** [JimiIT92/UniverseGuard2#64]
Hello,

I wanted to give myself all the perms from universeguard2, but i cant find any permission on the wiki...
When i look for a perm, i can only find: 

'PERMISSION

You must have the ALL permission to run this command'

So can someone please tell me where to find all the permissions? Would be great... Or just put them on the wiki??

~ SirMech1995

**Comment by JimiIT92** [comment]
In the current version these are the only permissions available. A proper permission system will be available with version 3 wich is currently in development and i hope to release it somewhere around the end of April or the beginning of May :)

**Comment by chippichoppa** [comment]
> In the current version these are the only permissions available. A proper permission system will be available with version 3 wich is currently in development and i hope to release it somewhere around the end of April or the beginning of May :)

Hi Jimil, I am writing to you from Ukraine. Now I am creating a server with mods on SpongeForge 1.12.2 and I ran into a problem. After creating a selection and creating a region (use /rg save), players can break blocks. Also, trying to give a name to a region (use /rg name), they write in a chat that I don’t have any regions. I use a translator but I think you will understand the problem :)

**Comment by JimiIT92** [comment]
Hi, probably the issue is that the flags for braking blocks are set to true. Make sure the destroy flag and all other relevant flags are set too, otherwise the Region won't protect from players breaking blocks
