### ISSUE TITLE
Players can use buckets in spawn

### ISSUE THREAD

**Issue by Solarmender** [JimiIT92/UniverseGuard2#65]
Hello. I disabled placing and breaking blocks in spawn. My players can right click on a liquid with a bucket in spawn. It doesnt remove the liquid but it gives them a full bucket. Then they are able to place it down somewhere else in spawn. Is there any way to disable this?

**Comment by Coolrooswag** [comment]
I am also having this issue

**Comment by Coolrooswag** [comment]
with my spawn I have these flags and people are able to place water buckets

 "FLAGS": [
    {
      "name": "place",
      "value": false
    },
    {
      "name": "destroy",
      "value": false
    },
    {
      "name": "pvp",
      "value": true
    },
    {
      "name": "expdrop",
      "value": true
    },
    {
      "name": "itemdrop",
      "value": true
    },
    {
      "name": "itempickup",
      "value": true
    },
    {
      "name": "enderpearl",
      "value": true
    },
    {
      "name": "sleep",
      "value": true
    },
    {
      "name": "lighter",
      "value": true
    },
    {
      "name": "chests",
      "value": true
    },
    {
      "name": "trappedchests",
      "value": false
    },
    {
      "name": "waterflow",
      "value": false
    },
    {
      "name": "lavaflow",
      "value": true
    },
    {
      "name": "otherliquidsflow",
      "value": false
    },
    {
      "name": "leafdecay",
      "value": true
    },
    {
      "name": "firespread",
      "value": true
    },
    {
      "name": "potionsplash",
      "value": true
    },
    {
      "name": "falldamage",
      "value": true
    },
    {
      "name": "cantp",
      "value": true
    },
    {
      "name": "canspawn",
      "value": true
    },
    {
      "name": "hunger",
      "value": true
    },
    {
      "name": "enderchests",
      "value": true
    },
    {
      "name": "walldamage",
      "value": true
    },
    {
      "name": "drown",
      "value": false
    },
    {
      "name": "invincible",
      "value": true
    },
    {
      "name": "cactusdamage",
      "value": true
    },
    {
      "name": "firedamage",
      "value": true
    },
    {
      "name": "endermangrief",
      "value": true
    },
    {
      "name": "enderdragonblockdamage",
      "value": true
    },
    {
      "name": "hidelocation",
      "value": false
    },
    {
      "name": "hideflags",
      "value": false
    },
    {
      "name": "hidemembers",
      "value": false
    },
    {
      "name": "hideregion",
      "value": false
    },
    {
      "name": "icemelt",
      "value": true
    },
    {
      "name": "exit",
      "value": true
    },
    {
      "name": "enter",
      "value": true
    },
    {
      "name": "vinesgrowth",
      "value": true
    },
    {
      "name": "sendchat",
      "value": true
    },
    {
      "name": "trample",
      "value": true
    },
    {
      "name": "shulkerboxes",
      "value": true
    },
    {
      "name": "pistons",
      "value": true
    },
    {
      "name": "frostwalker",
      "value": true
    },
    {
      "name": "fishingpole",
      "value": true
    }
  ],
  "INTERACTS": [
    {
      "BLOCK": "craftingtable",
      "USE": true
    },
    {
      "BLOCK": "enchantingtable",
      "USE": true
    },
    {
      "BLOCK": "itemframe",
      "USE": true
    },
    {
      "BLOCK": "armorstand",
      "USE": true
    },
    {
      "BLOCK": "anvil",
      "USE": true
    },
    {
      "BLOCK": "hopper",
      "USE": true
    },
    {
      "BLOCK": "lever",
      "USE": true
    },
    {
      "BLOCK": "button",
      "USE": true
    },
    {
      "BLOCK": "furnace",
      "USE": true
    },
    {
      "BLOCK": "door",
      "USE": false
    },
    {
      "BLOCK": "fencegate",
      "USE": true
    },
    {
      "BLOCK": "trapdoor",
      "USE": true
    },
    {
      "BLOCK": "sign",
      "USE": true
    }
  ],
  "VEHICLES": [
    {
      "VEHICLE": "minecart",
      "PLACE": false,
      "DESTROY": true
    },
    {
      "VEHICLE": "boat",
      "PLACE": false,
      "DESTROY": true
    }
  ],
  "EXPLOSIONS": [
    {
      "EXPLOSION": "tnt",
      "DAMAGE": false,
      "DESTROY": false
    },
    {
      "EXPLOSION": "creeper",
      "DAMAGE": false,
      "DESTROY": false
    },
    {
      "EXPLOSION": "endercrystal",
      "DAMAGE": false,
      "DESTROY": false
    },
    {
      "EXPLOSION": "fireball",
      "DAMAGE": false,
      "DESTROY": false
    },
    {
      "EXPLOSION": "enderdragon",
      "DAMAGE": false,
      "DESTROY": false
    },
    {
      "EXPLOSION": "otherexplosions",
      "DAMAGE": false,
      "DESTROY": false
    }
  ],

**Comment by Arkteus** [comment]
I have this problem too

**Comment by JimiIT92** [comment]
Is the Region located in the world's spawn chunk? If so it could be that the Vanilla spawn protection is taking over the plugin protection :/ You could also try disabling bucket items but is really strange that isn't working, are you using the lastest version?

**Comment by Arkteus** [comment]
Yes I am using the latest version but I am going to test /item use for this problem

**Comment by JimiIT92** [comment]
Fixed in version 2.18 :)
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.18
