### ISSUE TITLE
String issue

### ISSUE THREAD

**Issue by Coolrooswag** [JimiIT92/UniverseGuard2#66]
So I have place disabled in spawn and people are still able to place string, and water buckets 

UG2: UniverseGuard-2.17.jar
Sponge: spongeforge-1.12.2-2768-7.1.6-RC3616.jar

**Comment by JimiIT92** [comment]
Fixed in version 2.18 :)
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.18
