### ISSUE TITLE
Explosion damage flag not working

### ISSUE THREAD

**Issue by lolgamer252** [JimiIT92/UniverseGuard2#67]
Hi. I need this plugin for my server. I had in plans to use it as a griefprevention tool at spawn, but i couldn't find the flag for explosions. The server is on a modpack

**Comment by JimiIT92** [comment]
Try set the otherexplosions flag to false. Unfortunately many mods treat
explosions not like real explosions (they just remove blocks from the
world). Can you send me a list of mods you have on the modpack, so i can
test with that mods to find out how they handle explosions (or just the mod
responsible for that)?

Il ven 24 mag 2019, 11:27 lolgamer252 <notifications@github.com> ha scritto:

**Comment by lolgamer252** [comment]
I do not have the otherexplosions flag.. Tried to find it, but couldn't

fre. 24. mai 2019, 11:29 skrev JimiIT92 <notifications@github.com>:

**Comment by lolgamer252** [comment]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfri.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

fre. 24. mai 2019 kl. 12:08 skrev Leo Pichler <leopichler1@gmail.com>:

**Comment by JimiIT92** [comment]
Sorry, the correct syntax for that command is /rg flag explosiondamage otherexplosions false.
You can find more about the flag syntax in this wiki page ;) 
[https://github.com/JimiIT92/UniverseGuard2/wiki/rg-flag](https://github.com/JimiIT92/UniverseGuard2/wiki/rg-flag)

**Comment by lolgamer252** [comment]
I do not know if i have to open a new request, but there is another
problem. Players outside the region can not open their chests. They get a
message saying "you do not have permission to do that" over the 9 slots.
How can i fix this?


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfri.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

lør. 25. mai 2019 kl. 17:09 skrev JimiIT92 <notifications@github.com>:

**Comment by lolgamer252** [comment]
I got the chest thing to work, but now they have permission to do
everything. I wanted to use universeguard just for the spawn

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfri.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

søn. 26. mai 2019 kl. 10:55 skrev Leo Pichler <leopichler1@gmail.com>:

**Comment by JimiIT92** [comment]
Can you send me via PM your Region file?
