### ISSUE TITLE
players can use a lighter but it's not allowed

### ISSUE THREAD

**Issue by Arkteus** [JimiIT92/UniverseGuard2#70]
I blocked the use of lighters in my area but players can still use it.

Thanks to help-me.

here are my parameters:

   
[c3d25146-1761-468d-af33-cc0ac3dc53ed.zip](https://github.com/JimiIT92/UniverseGuard2/files/3365916/c3d25146-1761-468d-af33-cc0ac3dc53ed.zip)

{
      "name": "lighter",
      "value": false
    },

**Comment by JimiIT92** [comment]
Make sure your users don't have the region bypass permission set, i'll see if there are any problems with that flag. You could also try disabling the lighter item using the [/rg itemuse](https://github.com/JimiIT92/UniverseGuard2/wiki/rg-itemuse) command

**Comment by Arkteus** [comment]
ok I am going to test it

**Comment by JimiIT92** [comment]
Fixed in version 2.18 :)
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.18
