### ISSUE TITLE
Block breaking/placing

### ISSUE THREAD

**Issue by Crazysteef** [JimiIT92/UniverseGuard2#71]
Hi, When i turn off the flag of Destory and Place in the spawn it doesnt work how can we fix this issue?

**Comment by Crazysteef** [comment]
Honestly this plugin is so bad i tried everything but they can still break shit

**Comment by JimiIT92** [comment]
Show me your spawn Region file to see if everything is correct in it

**Comment by NoahDTheHorse** [comment]
yeah the same thing is happening to me, also it asks for dimension in the create region command, but then it asks for world, what the heck is the world, if it is not the dimension?

**Comment by JimiIT92** [comment]
world is the world name (typically world)
