### ISSUE TITLE
The Server crash when an player who don't have the permissions to break blocks try to break a block.

### ISSUE THREAD

**Issue by jul-fls** [JimiIT92/UniverseGuard2#73]
Hello, my server  is overloaded and the processor exceeds 400% of uses which pushes me to force him to restart ! when a player who don't have permissions to break blocks in regions tries to break blocks !

**Comment by JimiIT92** [comment]
Sounds strange, pm me your regions configuration and i'll see if i can find anything relevant to this

**Comment by jul-fls** [comment]
Yes but we have change for another plugin who works very well contrary to Universe Guard 2 !
