### ISSUE TITLE
My server has been warning in the background

### ISSUE THREAD

**Issue by denke123** [JimiIT92/UniverseGuard2#74]
My server has been warning in the background
https://paste.ubuntu.com/p/yD7XRC2TG4/

**Comment by JimiIT92** [comment]
That seems like a nucleus error, there could be something wrong there that is passed to the interact event wich is causing the warn

**Comment by denke123** [comment]
> 这似乎是一个核心错误，可能会有一些错误传递给导致警告的交互事件

How should I turn off this hint? Is there any way?

**Comment by JimiIT92** [comment]
You should contact the nucleus mod author and asks him what is causing that error
