### ISSUE TITLE
Infinite Paintings & Armor Stands

### ISSUE THREAD

**Issue by Killingman107** [JimiIT92/UniverseGuard2#75]
Sponge Version: 1.12.2-2825-7.1.6
UG2 Version: 2.17

Issue: When disabling placing & destroying in a world, players are able to left click an armor stand or painting as if they are destroying it. Doing so gives them an infinite amount of the item.

Example: https://gyazo.com/580d5791659f4ca70083052a8b32815e

I've tried changing the flags for all things relating to the mob "painting" and "pixelmon:painting"

**Comment by JimiIT92** [comment]
Already looking into that ;)

**Comment by Killingman107** [comment]
> Already looking into that ;)

Thanks a lot for the quick response! I'll keep an eye out for the update.

**Comment by JimiIT92** [comment]
Fixed in version 2.18 :)
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.18
