### ISSUE TITLE
Please add command restriction

### ISSUE THREAD

**Issue by joanros97** [JimiIT92/UniverseGuard2#79]
Hi, I'm using this plugin but I have a problem. When I was using world guard on my old server, I had a feature where I could ban commands like "/sethome, /tpaccept, /home...". This was really usefull because players could talk in the chat but they could not teleport with homes or TP.
In UG2 I didn't find this and I really need it. Could you add this option?

**Comment by JimiIT92** [comment]
There is /rg command, where you can allow or disallow a certain commands to be run inside a Region

https://github.com/JimiIT92/UniverseGuard2/wiki/rg-command

**Comment by joanros97** [comment]
oh, I see, thanks!
