### ISSUE TITLE
Travis CI misconfigured

### ISSUE THREAD

**Issue by Brycey92** [JimiIT92/UniverseGuard2#8]
On all of the commits using it, the Travis CI builds fail because the system can't find ".travis.yml" or a "rakefile." If Travis were working, we could use it for automated testing of the plugin, which would make development and bugfixing easier.

**Comment by JimiIT92** [comment]
I tried setting up the Travis CI build system but i'm missing something on configuration. Probably the .yml file i used was wrong, i'll try to make it work because is something really useful for builds ;)

**Comment by JimiIT92** [comment]
Fixed TravisCI configuration (or at least is now passing the builds on that) :D
