### ISSUE TITLE
two problems

### ISSUE THREAD

**Issue by donpacoperico** [JimiIT92/UniverseGuard2#80]
Hi, I have two problems.
1. When buying and selling regions, the problem comes when someone wants to sell the region, can sell it but does not earn the cost of the region, that is, the buyer takes 1 gold, but the seller does not earn anything.
2. By having a region, a player cannot add anyone as a member, that is, by using the '/ rg add member player' command, the answer is: the player does not have permissions to use the command, I have searched a bit and I saw that this command requires high permissions, is there any way that players can use the '/ rg add member player' command?

If you want I can help you with the development of the plugin.

I love the plugin I appreciate your work, I await your response.

**Comment by JimiIT92** [comment]
Hi, thank you for your appreciation :) For the first problem that sounds like a missing feature in the plugin, will patch that in the next one!
For the second one yes, the plugin was not meant to be a "faction-style" plugin, that is why players inside regions can't add players. A proper permissions system will come in version 3 (wich will come later next year) where you'll be able to define wich permissions are required to run each command (or set that a command has no permission to be run if you want too), but for now i'll see if i can find a workaround for this ;)

**Comment by donpacoperico** [comment]
Thanks for the speed when answering wow, a doubt, when will the next version come out?

And I repeat, the plugin is doing very well, if you need help in programming let me know.

Thank you very much for the attention and even another.

**Comment by JimiIT92** [comment]
I hope to release it someday next week ;)

**Comment by donpacoperico** [comment]
I will wait for you to do magic =)

**Comment by JimiIT92** [comment]
Version 2.20 has been released! Check it out! ;)
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.20

**Comment by donpacoperico** [comment]
Thanks!!! =)

**Comment by donpacoperico** [comment]
Out of curiosity, have you created a .json with the name of the player who sells the parcel and so when another player buys the parcel the one who has sold it will receive the money?

**Comment by JimiIT92** [comment]
This is done only if the player is offline. You will find a json file with the transactions, so when a player logs in it will check that file and give the rewards to the player. If the player is online than the reward is given instantly
