### ISSUE TITLE
Pixelmon Server default can't interact with pc or healer 

### ISSUE THREAD

**Issue by Coolboyz347** [JimiIT92/UniverseGuard2#81]
So I have made a region for the spawn. I set /rg flag interaction all true, /rg flag flag destroy false, /rg flag flag place false. Is there anything I did wrong? Defaults can't interat with pc or healer on spawn but the owners could.

**Comment by JimiIT92** [comment]
Wich version of Pixelmon are you using?

**Comment by Coolboyz347** [comment]
I solve it, by the way, I think it was a spawn protection setting. I'm using pixelmon 7.0.8

    On Friday, November 1, 2019, 03:17:28 PM EDT, JimiIT92 <notifications@github.com> wrote:  
 
 
Wich version of Pixelmon are you using?

**Comment by JimiIT92** [comment]
Glad you figured it out :)
