### ISSUE TITLE
Pressure plate flag

### ISSUE THREAD

**Issue by Angrigo** [JimiIT92/UniverseGuard2#82]
I can't find a pressure plate flag, is this a real problem?

**Comment by JimiIT92** [comment]
I remember i tried in an older version to add this flag, but the Sponge event was not working properly. Will try with the latest API and see if I can add it ;)

**Comment by Angrigo** [comment]
Thank you, I got it working now using the door flag, maybe they're someway
connected.

**Comment by JimiIT92** [comment]
It could be that the event that flag checks is the same fired off for pressure plates. If that is the case i might be split it up for clarity

**Comment by JimiIT92** [comment]
Version 2.21 just got released with this fix! Check it out ;)
[https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.21](https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.21)
