### ISSUE TITLE
Messages sent to the game

### ISSUE THREAD

**Issue by grishahsirg** [JimiIT92/UniverseGuard2#83]
Hello. In the file "universeguard.conf" translated the messages sent to the game into Russian, wrote in Cyrillic. Messages translated into Russian (written in Cyrillic) are not displayed. Instead of translating, it writes the source text in English.
How to solve a problem?
_Sorry for my English, I use Google translator._

**Comment by JimiIT92** [comment]
It sounds really strange, since I've just tested this, changing some texts to russian using google translate and it worked. Have you already restarted your server? Notice that any changes to that file won't take effect while the server is running
