### ISSUE TITLE
Doors of the maisisdoors without protection in the plots.

### ISSUE THREAD

**Issue by francescxavier** [JimiIT92/UniverseGuard2#84]
Hello again, I have a problem, I have added a mod of doors to the server and with the protection of doors activated in the plots, players can open doors. How can I add the mod doors to the protection.

**Comment by JimiIT92** [comment]
Short answer: right now you can't :/
Long answer: this is a flaw in the plugin I'm so sorry about, I'll fix it when I'll come back home around the first week of January :)

**Comment by JimiIT92** [comment]
Version 2.21 just got released with this fix! Check it out ;)
[https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.21](https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.21)
