### ISSUE TITLE
Could not pass MoveEntityEvent to plugin

### ISSUE THREAD

**Issue by HHServers** [JimiIT92/UniverseGuard2#85]
https://gist.github.com/HHServers/20644c20da4d20b9ac0706b3f1566de6
SpongeForge 7.1.7 1.12.2 recommended
Universe Guard 2.20

**Comment by JimiIT92** [comment]
Thanks for the report, will look and fix this as soon as I get home next week ;)

**Comment by JimiIT92** [comment]
Version 2.21 just got released with this fix! Check it out ;)
[https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.21](https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.21)
