### ISSUE TITLE
Inventory only for one region

### ISSUE THREAD

**Issue by ChukiStrike** [JimiIT92/UniverseGuard2#87]
Hi, I want all your items to be lost when you leave the region. So they can't give anything from that region to another.

**Comment by JimiIT92** [comment]
That's really rude! Anyway I can think a flag to do this ;)

**Comment by ChukiStrike** [comment]
Thanks you!!

**Comment by JimiIT92** [comment]
One problem I see here, however, is that if a player has some items before entering the region he'll lost them when he leaves, even if he didn't take any item from the region

**Comment by ChukiStrike** [comment]
Can't you keep things from each region? That would be great!
Anyway, I think it would go very well, because if you limit an area to build something for your city, for example, your builders who have creative will not be able to give anything to the others because when they leave the region they will be lost. You can inform them to come with nothing already :)
