### ISSUE TITLE
Error when we go to the nether.

### ISSUE THREAD

**Issue by ChukiStrike** [JimiIT92/UniverseGuard2#88]
Error when we go to the nether. Fix it please! We need go to nether.
Error code:
https://pastebin.com/2FA8XsK0

Thanks you!

**Comment by JimiIT92** [comment]
Thank you for the report, will look into this ;)

**Comment by ChukiStrike** [comment]
I checked that the error is because the DIM-1 dimension is not set. So I found the earwig and created it myself and it works.

**Comment by JimiIT92** [comment]
Glad to hear that :) I've also found a potential bug in that flag code, so it was still a useful report :)
