### ISSUE TITLE
Mob spawning

### ISSUE THREAD

**Issue by Richi-SH** [JimiIT92/UniverseGuard2#89]
Is there any way to avoid mobs from spawning inside your region?

**Comment by JimiIT92** [comment]
Yes, there are flags related to mobs in general [https://github.com/JimiIT92/UniverseGuard2/wiki/rg-flag](https://github.com/JimiIT92/UniverseGuard2/wiki/rg-flag), but I guess you already figured it out by yourself ;)

**Comment by Richi-SH** [comment]
Yeah, I eventually found it! Thank you very much anyway!
