### ISSUE TITLE
Chest flag isn't working

### ISSUE THREAD

**Issue by swedax** [JimiIT92/UniverseGuard2#91]
Hi there!
We have a problem with the chest flags. I set the flag in config to true. However, after a server restart, players can only access in the global world, if I have previously set it to true via command. During the start there are no conspicuous entries in the log.

Forge Version: forge-1.12.2-14.23.5.2838

**Comment by JimiIT92** [comment]
Looks strange, can you send me via PM the region file for one region where the flag isn't working correctly?
