### ISSUE TITLE
Players can´t open a chest in all world.

### ISSUE THREAD

**Issue by DavidVentrue** [JimiIT92/UniverseGuard2#92]
Hello!

My server players cannot open any chests outside any region, unless they are in OP. I don't want this, but I can't find the command to change the use of all chests to "true."

**Comment by JimiIT92** [comment]
You have to set this flag for all regions one by one, unfortunately there is no "massive edit" at the moment

**Comment by DavidVentrue** [comment]
The problem is that it is not only in the regions. Outside of limited regions, that is, anywhere in the world, it does not allow us to open any chest.

**Comment by JimiIT92** [comment]
That's probably because the global region is preventing players from opening chests. Can you please send me your global region file and a local region file where this is happening?

**Comment by DavidVentrue** [comment]
I have already solved. By telling me that the global region was interposing with the local regions I realized that the flag of chests in the global region was false. Thank you :D
