### ISSUE TITLE
Unselect regions and clickable flag

### ISSUE THREAD

**Issue by Furtii** [JimiIT92/UniverseGuard2#93]
I can't unselect a region after typing the /rg edit command (Seems to be the only way ton change flags on an existing region), need a command to unselect the region currently editing without having to save it or anything.

Also, can you add a feature to click some flags in the /rg info command to toogle them true/false ? 
It would be awesome

**Comment by JimiIT92** [comment]
A command to unselect a Region is currently in development. While for clickable flags that is something planned from a while, so I'll see if I can add them in next or future releases

**Comment by Furtii** [comment]
Thanks for the fast reply, i'd like to help but i'm not very experimented with this kind of programs, anyway, tell me if i could help by testing on anything else, thank you for your work

**Comment by JimiIT92** [comment]
Clickable flags and the ability to discard changes has been added into latest version! Check it out 😉
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.22
