### ISSUE TITLE
UniverseGuard Does Not Protect 'Microblocks' From 'ForgeMultipart'.

### ISSUE THREAD

**Issue by Champion0912** [JimiIT92/UniverseGuard2#96]
Just got a report from my developer yesterday that Universeguard does not protect microblocks (ForgeMultipart mod) from being destroyed.

It's still a bit early to create this issue as I don't have much information yet.

We will update our server to newest versions of Forge Mod Loader and ForgeMultipart and get back to you if the issue is continuing to exist.

I cannot see any errors or similar in our logs so please get back to me with whatever information you'd appreciate us to provide so we can find a quick fix for this.

**Comment by JimiIT92** [comment]
Version 3, with the Microblocks fix, has just been released! Check it out!
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/2.23
